### ISSUE TITLE
Incorrectly rending all GUI box nodes with 9-slice vertices (DEF-3880)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3181]
From forums: https://forum.defold.com/t/rendering-gui-nodes-def-3880/47617

**Comment by britzl** [comment]
comp_gui.cpp in RenderBoxNodes():

https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L1060

There is a boolean set early on in the function to figure out if 9-slice is enabled or not: 

https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L1133

**Comment by hapass** [comment]
@britzl 
This might be not as bad as described in the forum though… If box node has texture - it is drawn [with 2 triangles](https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L1140-L1187) and the only case I can definitely optimize is no texture (white texture) - this case is exactly as seen on the screenshot from the forum - it takes [18 triangles to draw](https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L1253-L1315).

Also [PRIMITIVE_TRIANGLES is used](https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L1096) to draw box node and it is drawn without indices. Maybe it is [done for a reason](https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L1167), I need to double check, but we might use indices or different primitive type here to submit less stuff to draw.

**Comment by britzl** [comment]
Interesting. I wonder why it's done like that to be honest. @JCash any idea?

**Comment by hapass** [comment]
@britzl @JCash 
I've changed the code, so that if there is no texture we render just 2 triangles that form a white square. I'll wait a little bit before creating PR I guess, cause maybe we'll decide this needs more optimizations or even that this change solves a rare case and is not that important.

Here is a link to branch compare: https://github.com/defold/defold/compare/dev...hapass:Issue-3181-gui-box-node-renders-extra-vertices?diff=unified 

Texture, **no** 9 slice params:
<img width="806" alt="Screen Shot 2020-06-05 at 02 34 09" src="https://user-images.githubusercontent.com/23015779/83821776-f366c700-a6d7-11ea-9711-34dc9a9aa61c.png">

**No** texture, **no** 9 slice params:
<img width="674" alt="Screen Shot 2020-06-05 at 02 35 06" src="https://user-images.githubusercontent.com/23015779/83821800-09748780-a6d8-11ea-99eb-9062ddaa7e6c.png">

**No** texture, **with** 9 slice params:
<img width="740" alt="Screen Shot 2020-06-05 at 02 36 54" src="https://user-images.githubusercontent.com/23015779/83821847-214c0b80-a6d8-11ea-925f-6aeb8ccaad78.png">

Texture, **with** 9 slice params:
<img width="729" alt="Screen Shot 2020-06-05 at 02 39 39" src="https://user-images.githubusercontent.com/23015779/83821880-3e80da00-a6d8-11ea-8dbd-893404c176ad.png">

Pay attention to the **Gui.VertexCount** counter that I've set in the code. This counter is how I tested the solution. I've also tried to use open gl profiler on mac, but it was very slow and glitchy for me and I failed to collect required data with it, maybe I'll use webgl target a bit later, it has some good profilers.

**Comment by JCash** [comment]
I cannot definitively tell why we're not using indices.
My guess is for historical reasons on older phones.

**Comment by JCash** [comment]
I think this change seems very good.

**Comment by britzl** [comment]
Ok, so let's go head and create a PR @hapass !

**Comment by hapass** [comment]
I've created the PR: https://github.com/defold/defold/pull/4880. I wasn't creating it right away cause I took time to investigate how sprite trimming might affect the amount of vertices rendered here :) I will investigate a little bit more, but if you know for a fact that GUI is not affected by sprite trimming please tell me. @britzl @JCash

**Comment by britzl** [comment]
> but if you know for a fact that GUI is not affected by sprite trimming please tell me

@JCash ?

**Comment by hapass** [comment]
@britzl @JCash 
So I have finished investigation of sprite trimming. 
Here are some weird things I noticed:
1. We do not respect m_UseGeometries option when rendering GUI box. There is only one path for rendering GUI box without 9 slice params and with texture and it uses hull indices, which are calculated always, and it ignores m_UseGeometries option. This probably isn't an issue - theoretically we should have m_UseGeometries option set to true when we calculate hulls but this isn't the case.
2. It seems that there is code duplication in pipeline code. And as a result m_UseGeometries option is only set when packaging application, it is not set when building it inside the editor. But hulls are calculated anyway. This seems weird, and as a result of first "issue", we get 18 vertices rendering on both packaged and built application, however m_UseGeometries option differs in those two.
3. The spaceship gets invalid hulls, although this might not be a problem, but I then substituted spaceship with white dot and got the 18 vertices box rendering like I was suspecting.

Box with texture, **no** 9 slice params:
<img width="716" alt="Screen Shot 2020-06-09 at 19 08 17" src="https://user-images.githubusercontent.com/23015779/84174645-8791af00-aa87-11ea-9c00-df25dcd43054.png">

Same thing with 9-slice params will get 54 vertices, as 9 sliced node rendering ignores SpriteGeometry hulls.

**Comment by britzl** [comment]
Thank you for your research! @JCash your input is needed!

**Comment by JCash** [comment]
1) Not sure what you're referring to here. We do use sprite trimming for non-slice-9 box nodes,
as seen in comp_gui.cpp:

    // we skip sprite trimming on slice 9 nodes
    if (!use_slice_nine && use_geometries)
    {
        int32_t frame_index = dmGui::GetNodeAnimationFrame(scene, node);
        frame_index = texture_set_ddf->m_FrameIndices[frame_index];

        const dmGameSystemDDF::SpriteGeometry* geometry = &texture_set_ddf->m_Geometries.m_Data[frame_index];


2) the editor _should_ calculate the hull vertices, _and_ set the `use_geometries`flags.
If it doesn't, it'a a bug.

3) Not sure what you mean by "invalid" hulls. Needs more info.
