### ISSUE TITLE
If a key is held down while HTML5 build has focus and then another window gains focus the key continues to say it is held down (DEF-2787)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3186]
Description:

Steps to reproduce:

Expected result:

Actual result:

**Comment by ConnorHalford** [comment]
Any updates on this?

I tried to create a workaround but it doesn't seem possible. I could store the set of action_id that are held when focus is lost, and after focus is regained continue to ignore them until a new real press event occurs. However when the key is actually pressed again no press event occurs since Defold considers the input to have already been held anyway. So you would have to ignore the input until a release event occurs, but pressing and releasing the key solves the issue anyway since the key really isn't 'held' anymore at that point.

So the possible user experiences are: "this input is constantly firing, but I can press it again to fix it", or with the attempted workaround "sometimes my inputs get ignored for a reason I don't understand" which is even worse.

**Comment by ConnorHalford** [comment]
Since the issue occurs when the canvas loses focus, it may not even be that the user clicked on a different program or different browser tab, they may have just clicked outside of the game itself onto the page it is embedded on.

**Comment by britzl** [comment]
> Any updates on this?

No, no update on this. But I'll add it to the list of tasks to investigate for next release.

**Comment by ConnorHalford** [comment]
Thank you!

**Comment by britzl** [comment]
From forum (https://forum.defold.com/t/defold-1-2-193-beta/70405/11?u=britzl):

Focus loss and gain for the embedded HTML5 build are printed when:

* The browser is minimized and restored while the game tab is focused (even if the game itself is not focused)
* A different maximized program on the same monitor is Alt-Tabbed to
* A different tab in the same browser window gains focus (mouse click or keyboard shortcut)

Focus loss and gain are not printed when:

* Focus moves between the game and the page it is embedded in
* Focus moves to a non-maximized program on the same monitor (mouse click or Alt-Tab)
* Focus moves to a maximized program on a different monitor (mouse click or Alt-Tab)
* Focus moves to a browser tab in a different window (mouse or keyboard shortcut)

There may be other relevant scenarios.
