### ISSUE TITLE
go.property parsing unforgiving (DEF-3648)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3342]
Reported here; [(LINK REMOVED)

Our parser for go properties is unforgiving. The code below (notice the space) on HTML5 will not register the property.

    go.property ("prop", val)

In this case

    self.prop

will return nil.

**Comment by britzl** [comment]
https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaScanner.java#L59

**Comment by britzl** [comment]
Thank you!

**Comment by thejustinwalsh** [comment]
Looks like something like this breaks the LuaScanner as well...
```lua
go.property(
    "dir",
    vmath.vector3(0, 1, 0)
)
```

**Comment by thejustinwalsh** [comment]
@britzl open to a PR to resolve the above? Should this issue be re-opened or would you prefer a new issue?

This issue is a problem for supporting something like source-maps when transpiling to lua. I can modify my tool to collapse the calls, but then any source mapping I am attempting to do would not longer line up. The regex required to parse this gets a bit more complicated but I think it would be a nice addition.

Are there tests for these parser tricks when targeting HTM5?

**Comment by britzl** [comment]
@thejustinwalsh We'd love to get a good PR that fixes this! It's ok to re-open this issue.
