### ISSUE TITLE
Occlusion culling

### ISSUE THREAD

**Issue by britzl** [defold/defold#3406]
Currently everything is sent to the gpu. Even if it is outside the frame. We need frustum culling to reduce the number of draw calls and the amount of vertex transforms being made. 

_EDIT 2021-12-29:_
Here are some initial thoughts on design/requirements:
https://docs.google.com/document/d/1N24ND82UbUD7RXsZBwyrYEiIqPJZ6ma4Ed0zd8CzdeE/edit?usp=sharing

**Comment by JCash** [comment]
Just a note that the idea is to provide an api where the developer can get a callback, with a buffer with the relevant spatial data (e.g. aabb's), and return another (same?) buffer, with some data filled in (e.g. culled = 1).

**Comment by paweljarosz** [comment]
Hi! I am very interested in how is it going, this is a big feature - do you have already some ideas on how to do it or wasn't it yet planned? ;)

**Comment by britzl** [comment]
> I am very interested in how is it going, this is a big feature - do you have already some ideas on how to do it or wasn't it yet planned? ;)

We have some ideas but nothing more yet.

**Comment by dlannan** [comment]
Hi, Ive had a very quick skim of the doc, and have a few quick Q's. 
1. Are you wanting final phase frustum culling or something a little earlier in the pipeline?
2. I think LODs and Frustum culls are a bit different process (LODs are not necessarily tied to the frustum). Is this likely to be a separate piece of work? 
3. Would Bounding Boxes be part of an overall "scene manager" ?

A few of the features appear to be more scene management like, which kind of then starts the discussion of scene organization systems - Octrees, Isosurfaces, BSP et al. 

This might be worth making a scene management API - where the developers can define their preferred organization methods and maybe even camera/frustum culling methods? 

The engine then just dumps the object pool to the API and the developer processes it as they need. A default process method could be added (octree for example) and a basic frustum culling process, as well as a basic LOD. 

I suspect that with 2D and 3D usage and the breadth of use of Defold (how people use it) there may be value in not locking in any specific system for this?

**Comment by JCash** [comment]
Hi @dlannan !

For the frustum culling part, we'll likely use something like ([BFBC](https://www.humus.name/Articles/Persson_CreatingVastGameWorlds.pdf) for the actual check (I'll see if I can get hold of some old source code for that).
We want it a early enough in the pipeline, since we need it to send messages to the scripts.
The scripts can then determine if the game object should be deleted, be disabled or whatnot.

The term "Frustum" in the task description is a bit misleading, as we want multiple features.
It's not _just_ about the culling with respect to the frustum, but we need to consider other things as well.
They're all connected, and we need to consider this before jumping in an implement a solution.
E.g. in the future, we also want occlusion culling, which should be possible to tie into the same messaging pipeline.

I think step one is outlining the most common use cases, and some of the features we want/need. Then we can see what incremental steps we can take in order to improve performance for the games.

As you know, we don't really have any other management of our scene than a scene graph for a collection, and a list of components. In most cases, a brute force check is most likely more than enough, whereas some games might require a better organization. A full scene management api is probably not what we want/need, I think we can default to some spatial structure (Octree or something). It can probably be extensible as well with a native extension. But perhaps I'm missing something?

I think we do want good defaults though, so we need to be able to have something that works for both 2D/3D, but as you say, we want something that is easy to swap out later on.

**Comment by dlannan** [comment]
@JCash 
'We want it a early enough in the pipeline, since we need it to send messages to the scripts.
The scripts can then determine if the game object should be deleted, be disabled or whatnot.'

Ok. That is a nice way to develop a feature requirement :)  I understand the implications too so its important to do the right type of development.

Id agree that brute force is a great simple naive approach and would just be wary of how that interface is implemented. Some of these types of scene management features can have long term ramifications. 

On occlusion culling, the trick will be using the right scene org for it. Octree is good quick (and relatively simple) manner for handling many of these types of scene raycast related events and searches. Works well with 2D or 3D. (2D being only 2 axis of the Octree). 

One thing I have been thinking of, is a referential access pool for objects. By this I mean that all the objects are available in some basic format (list, hashmap, array etc) and then the scene tools/processes can simply use these lists as inputs to their operations, with a mix/collation phase of their output to go to the event engine, physics engine and render engine. This is one idea of implementing a fairly open API setup that has low impact on the current codebase, while still maintaining the current Defold SDK. Even more ideally, have these systems as extensions?

I did build an ISO surface system for physics, pathing, culling and collision in luajit. It should work fine in Defold as a lua module, so it might be an interesting process to see if it could be made as a "selectable" addition to Defold rather than necessarily embedding too much into the SDK itself.

Im not making any concrete suggestions here, since I need to do some research into the SDK first to make sure Im not making suggestions that might not be feasible anyway :)  But I guess native-extensions and lua modules might be a nice way to trial some ideals without having to get too far into the SDK. If be keen to hear your thoughts on that - Ie would it be worth me porting a few of these systems to NE's or modules just to trial some ideas?

**Comment by JCash** [comment]
I also realized that for occlusion culling, we might actually want to use the GPU.
Previously, we've been restrictive with respect to using GPU implementations due to our support for lowend devices, but I also feel that it limits us to a large degree. And nowadays, most devices are quite powerful so it might not be a problem to aim for GPU support only there.

Regarding your api suggestion, I'm not sure how that api would be used?
One major design idea behind the engine is that the users shouldn't traverse it all the time to make queries in the screne graph. That will quickly escalate and at the end of the project, you have a code structure that is not easy to refactor/optimize.

My idea is that we have specific api functions for specific tasks. E.g. culling objects.

**Comment by dlannan** [comment]
Occlusion culling on GPU should be doable. You could have CPU or GPU options there - switchable in the project?
Most devices have OpenGLES support these days (at least 2.0) and so keeping GPU programs using that or Vulkan would be fairly cross platform -Vulkan might be a little trickier. 

The API idea would be something that allows a way to reduce your final GPU render submit data pool (game objects etc). 
It could be done in many ways, my thoughts are so you dont lock yourself into a solution that complicates the SDK in the long run. 

In the engine you would have staged passes:
1. Coarse cull for general local gameobject sorting and event publishing (like a sphere tree or something similar - fast/simple)
2. Finer go cull for Cameras (will need to do for each camera), collision and physics
3. Finer still cull for occlusion, light probes, similar. 
This as a very 'broad' description of course. Each 'phase' could be a method for Gos to return a flag for enable/disable ( this is probably quite expensive call overhead) or you could have a phase object list that the external phase can run. 
By this, you have a callback (SDK method) that can ben hooked to. The input params is a list of all the objects that need to be assessed - then the developer can return a sub list. The general use would be that normally all phases are internal to SDK, with maybe go flag exposure, but if a developer wants, they can plug into a phase step and then define what go's they want to get to the render or physics engine. 

This is all just thinking out loud at the moment. We did this sort of thing in the past with distributed sims. It main advantage, is if someone makes some awesome occlusion culling method, you can quickly benefit from it. Additional benefits are access to go information that could allow for very different go handling pre-render - for example, location based update LODing for events and ai (go's that arent close can still be updated at a controlled rate).

I think the api functions is fine too. You may find the list of tasks to become quite substantial :) .. lods (anim, static, events,, physics), frustum culls, occlusion, searching/raycasting, physics culling, audio culling and so on. Many of these could be combined in a single or a couple of api calls though. 

I think the question would be - do you want the culling to be tightly coupled to the SDK, or loosely. Im not advocating either honestly :) .. in the long run its about getting a tool to do something you need it to do :)

**Comment by JCash** [comment]
As for the api, I'm thinking something really simple and easy to replace with custom implementations.
E.g. along these lines:
```
// In information. Really shouldn't need more info here,
// as the caller can use the index into the array to look up things on the caller site
struct CullObject
{
    OOB m_Box; // Really should keep the size small for cache reasons
};

// out information
struct CullResult // default 0
{
    u8 m_Lod : 4;
    u8 m_FrustumCulled : 1;
    u8 m_OcclusionCulled : 1;
    u8 : 2;
};

// The out array has same length as the oobs
void CullObjectsFrustum(Frustum frustum, int num_objs const CullObject* objects, CullResult* out);

.. and other functions for e.g. occlusion culling
```

The type of objects, I imagine are game objects, since our components cannot move in relation to their "owner".

> this is probably quite expensive call overhead

I'm assuming you talk about Lua here, and sure it might be possible/relevant to do some queries from Lua.
However, I don't see it as the main part of the task, but perhaps more of a later improvement.

I think the real issue might be the overhead of sending multiple events (i.e. one each for each game objects). There are ways to mitigate that:
* Only send events when the cull state changes
* Don't send the data one-by-one, but in an array. It would require a "listener" callback, which would be more unwieldy, and would most likely contain sending events to the actual objects anyways.
* The script might need to "subscribe" to this type of events. That way we can early out on the C++ side.

> You may find the list of tasks to become quite substantial

Ofc.This is a part of the engine that hasn't been worked on and there sure are a lot of design decisions to take.

**Comment by dlannan** [comment]
Yes, I was referring to lua callbacks, in fact the majority of what I am looking at doing myself is completely in lua (no C at all). This is how we roll at my workplace :) .. the C is a pure functional blocks. The lua script is where all the "management" is done. It simplifies the size of the interface you need to build to functional components  - but thats a whole different architecture discussion :)

Quick q. Is this mainly for rendering? It should work fine for that, but I think you'd need to add more info if you want it for say physics or ai. Ie - you need to have go id or something to know which bb you are trying to cull. 
I guess technically you could hash the bb and keep a handle lookup table which might be ok.

I assume you are referring to cull events to notify objects of their cull status or state change? 
You could potentially bypass the need for this, and have a "cull event list" when running the cull method. Then the developer can decide if they need to send events to that list for processing. Itd be another output llist/array but would allow the developer to decide on how much event notification they want to push to the system. 
A possible example: The occlusion cull frustum returns no events, and only the main camera cull returns a list of events that notifies affected go's. 
Just a thought. 

Generally I think that setup looks pretty good and should get things going at least :)

**Comment by rocamocha** [comment]
Just read the whole thread and would like to just point out that I'm very excited for whenever this feature comes!

**Comment by aglitchman** [comment]
Great conversation! I hope that you will make some progress soon, and Defold will have bounding boxes + frustum culling shortly. And I just want to advise you that sometimes it is not viable to make something that will fit all needs, and it's better to start from the basic implementation and see how it goes.

By the way, I implemented frustum culling using the current features of Defold, i.e. you can calculate the visibility of meshes by camera matrices and disable/enable meshes. How it works:
- Render script [saves camera proj*view matrix](https://github.com/indiesoftby/defold-scene3d/blob/main/scene3d/render/render3d.render_script#L56).
- `frustum_mesh` [scripts](https://github.com/indiesoftby/defold-scene3d/blob/main/scene3d/scripts/frustum_mesh.lua) & [C++ code](https://github.com/indiesoftby/defold-scene3d/blob/main/scene3d/src/extension.cpp#L180) helps to track the visibility of meshes.
- The result from the [visibility check function](https://github.com/indiesoftby/defold-scene3d/blob/main/scene3d/src/extension.cpp#L232) is a message that you can send to the mesh - `disable` or `enable` or nothing.

That's enough to do basic frustum culling, but some drawbacks are there. For example, you can't do frustum culling for different cameras, and my implementation uses camera matrices from the previous frame.

**Comment by AGulev** [comment]
I agree with Mathias and Artsiom, that it would be great to implement it step-by-sep and start with MVP1 where engine just turn off rendering components. Even this one feature will give a huge benefits in big projects.

**Comment by britzl** [comment]
> * Render script [saves camera proj*view matrix](https://github.com/indiesoftby/defold-scene3d/blob/main/scene3d/render/render3d.render_script#L56).

> you can't do frustum culling for different cameras, and my implementation uses camera matrices from the previous frame

Could we help with this somehow? New functions in camera.* maybe? Or new properties which you can only go.get()?

https://defold.com/ref/stable/camera/

**Comment by dlannan-fmad** [comment]
@AGulev I think that is a very good idea. Give access to capability, and let the developer decide on how the culling is applied. 

One thing I think could make this possible is access to the predicate render list in the render script. (so we can manage their order, or add/remove to the list) or add an enable flag to an element in the render list.

**Comment by JCash** [comment]
#6439 Is now done in its first form, supporting frustum culling for sprites.
It's in on the dev branch, and should be available for testing in an hour.

**Comment by 8bitskull** [comment]
Appreciate the work so far, #6439 is great! I'm here to provide a couple of use cases from an every day user.

It has been discussed already in the thread, but I would like to provide some actual examples. What I want is for the culled state of an object to be queryable and/or broadcast to subscribers (which may or may not be the object in question).

**1) Enemies off-screen**
In most games, enemies have complex and sometimes costly behaviour patterns: Movement and positioning, attack targeting, etc. Knowing that the enemies are off screen would enable me to either entirely disable their behaviour (even their script component, if they have one) or just run something simplified, like go.animate() to move towards the player.

**2) Looping background objects (e.g. starfield parallax)**
This is pretty simple really but detecting when a star goes off one side of the screen would enable me to loop it around the other side. Like I said, this isn't complicated, but making it work with whatever camera/rendering/adjust solution is currently in place always ties me up in knots.

In both of these examples, it might be the case that the game objects in question do not have a script component but are instead managed by a centralised controller script. In this case, it would not be sufficient for the game object in question to receive a culling state change message (as is the case for collisions). I can't see any solution other than a) other scripts being able to query the culling state via a function, or b) scripts being able to subscribe to state changes that would be then passed via messaging.

**Comment by Morgerion** [comment]
It's time for meshes and models!
Frustum culling works great on sprites, but it's still not available for models, which puts me in a difficult position when developing the shadow-casting.

![image](https://user-images.githubusercontent.com/7888071/172597337-c02e6ad9-6958-451b-9075-883afd6dca2e.png)
![image](https://user-images.githubusercontent.com/7888071/172597497-ba54b122-b222-409b-9533-4e8138182717.png)

**I so want to do shadows in all these projects!
But it's really hard and sad without frustum kulling for meshes.** :(

**Comment by britzl** [comment]
Split this into two new issues, one for frustum culling and one for occlusion culling:

* https://github.com/defold/defold/issues/6939
* https://github.com/defold/defold/issues/6934
