### ISSUE TITLE
Framing does not work in debugger for long file names (DEFEDIT-1690)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3835]
Break points seem to be hit but no visual indicators of which line the debugger stopped on work for script files with long file names.

**Comment by coderm4ster** [comment]
I’ve been investigating what’s causing the problem. There is a limit to the length of Lua source paths in the bob and editor source. In both places, the paths are limited to 59 characters during the build.

https://github.com/defold/defold/blob/c2cf0b6131777465a03c71a41308ed2b49876ade/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java#L130

https://github.com/defold/defold/blob/c2cf0b6131777465a03c71a41308ed2b49876ade/editor/src/clj/editor/luajit.clj#L32

There is also a note in the bob source code about this:

// We will also limit the chunkname (the identifying part of a script/source chunk) to 59 chars.
// Lua has a maximum length of chunknames, by default defined to 60 chars.

It seems to me that something misunderstood may have happened here. During debugging, the editor uses mobdebug to retrieve current debug status information. Mobdebug uses the debug.getinfo(i, “Snl”) function call to determine the current source, line number, and so on. If you read the lua_getinfo function and its lua_Debug structure in the Lua documentation (Lua 5.1 Reference Manual), you can see that the 60 character limit (LUA_IDSIZE) only applies to printable source names (short_src). Since the editor does not use the short_src attribute (but the content of the source attribute that has no character constraint), I don’t think the 59 long character constraint above makes sense. Developers could say more about that.

I removed this restriction in the bob and editor source and then build the engine and editor as well. During testing, the long path was no longer a problem.

**Comment by britzl** [comment]
I believe the problem we tried to solve was how Lua errors and stack traces were displayed. If a Lua chunkname starts with `=` [the first 60 characters will be copied](https://github.com/defold/defold/blob/dev/engine/lua/src/lua/lobject.c#L183-L186) as is to `short_src`. For a long path this means that the important part (the filename) will not be included in `short_src`.

Now the question is why do we prefix with `=`? If we look at the [`luaO_chunkid` function](https://github.com/defold/defold/blob/dev/engine/lua/src/lua/lobject.c#L182) we see that if the chunkname starts with `@` the function will include the last part of the path, prefixed by `...`. Why didn't we decide to use this and why did we opt for doing our own thing in LuaBuilder.java and luajit.clj? Our solution results in problems with the debugger outlined in this issue.

Here's an example of the output with the current version of bob/editor when this function is called:

```
-- main/something/really/deep/and/nested/thisisaveryveryveryveryveryveryveryveryveryverylongluamodule.lua
function M.greet()
	print("Hi there!")

	print(debug.traceback())
	local info = debug.getinfo(1, "Snl")
	pprint(info)
	error("foo")
end
```

Output:

```
DEBUG:SCRIPT: Hi there!
DEBUG:SCRIPT: stack traceback:
	saveryveryveryveryveryveryveryveryveryverylongluamodule.lua:7: in function 'greet'
	/main/main.script:5: in function </main/main.script:4>
DEBUG:SCRIPT: 
{ --[[0x10ac23b00]]
  short_src = "saveryveryveryveryveryveryveryveryveryverylongluamodule.lua",
  linedefined = 4,
  lastlinedefined = 12,
  what = "Lua",
  name = "greet",
  namewhat = "field",
  currentline = 8,
  source = "=saveryveryveryveryveryveryveryveryveryverylongluamodule.lua"
}
ERROR:SCRIPT: saveryveryveryveryveryveryveryveryveryverylongluamodule.lua:10: foo
stack traceback:
  [C]:-1: in function error
  saveryveryveryveryveryveryveryveryveryverylongluamodule.lua:10: in function greet
  /main/main.script:5: in function </main/main.script:4>
```

* The call to `debug.traceback` shows the last 60 characters of the path. Good!
* The `source` field of `debug.getinfo` shows the last 60 characters and not the full path. Bad (see issue).
* The call to `error` shows the last 60 characters of the path. Good!

Now what if we modify LuaBuilder to not limit the chunk name to 60 characters and prefix the name with an `@` character. Here's the output:

```
DEBUG:SCRIPT: Hi there!
DEBUG:SCRIPT: stack traceback:
	...eryveryveryveryveryveryveryveryveryverylongluamodule.lua:7: in function 'greet'
	main/main.script:5: in function <main/main.script:4>
DEBUG:SCRIPT: 
{ --[[0x112a9af20]]
  source = "@main/something/really/deep/and/nested/thisisaveryveryveryveryveryveryveryveryveryverylongluamodule.lua",
  short_src = "...eryveryveryveryveryveryveryveryveryverylongluamodule.lua",
  linedefined = 4,
  lastlinedefined = 12,
  what = "Lua",
  name = "greet",
  namewhat = "field",
  currentline = 8
}
ERROR:SCRIPT: ...eryveryveryveryveryveryveryveryveryverylongluamodule.lua:10: foo
stack traceback:
  [C]:-1: in function error
  ...eryveryveryveryveryveryveryveryveryverylongluamodule.lua:10: in function greet
  main/main.script:5: in function <main/main.script:4>
```

* The call to `debug.traceback` shows the last 60 characters of the path. Good!
* The `source` field of `debug.getinfo` shows the full path. Good!
* The call to `error` shows the last 60 characters of the path. Good!

**Comment by britzl** [comment]
I've been testing the debugger with the `@` change above and I can't get the breakpoints to hit despite changing in both mobdebug.clj and luajit.clj.

The debugger does work as expected when using `=` (and removing the 60 character source path limit).

**Comment by coderm4ster** [comment]
Yes, I have this problem too. In the meantime, I found the solution. The @ character must not be passed to the SETB and DELB commands.

Using the @ character is a better choice than the = character because, as you wrote, it puts the path abbreviated with "..." in the short_src attribute. However, this will break the breakpoint hit check in mobdebug.lua.

Look in the source of mobdebug.lua to see that the @ character is removed from the source path in the debug_hook function, so there will be no breakpoint hits.

https://github.com/defold/defold/blob/d63974dc8085c3dc65058a847989e55279b46d24/editor/bundle-resources/_defold/debugger/mobdebug.lua#L636

**Comment by britzl** [comment]
> Look in the source of mobdebug.lua to see that the @ character is removed from the source path in the debug_hook function, so there will be no breakpoint hits.

Yep, I just found this!

**Comment by britzl** [comment]
> The @ character must not be passed to the SETB and DELB commands.

I've updated mobdebug.clj to not include the "@" character. The latest commit to the PR should solve everything, at least according to my testing.

**Comment by coderm4ster** [comment]
Yes, it's perfect, it works for me too!

As a result of this fix, you may also want to improve the printing of source file paths in the editor call stack view to retrieve data from the short_src attribute. Currently, the source attribute is used there as well. For this reason, a lower scrollbar appears for long paths.
