### ISSUE TITLE
Feature request: Single/multiple instance mode (DEFEDIT-1590)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4075]
As a developer, I want to be able to run multiple instances of the game from one editor instance. For example, when testing multiplayer, it can be very usefull to have more than one instances of the game running. Bundling it every time makes process really slow. It would be really good if you could specify if the editor should allow multiple instances of the engine running.

For example IntelliJ IDEA has this option.

**Comment by AGulev** [comment]
Merged from https://github.com/defold/defold/issues/4035

```
Description:
When developing multiplayer games it would be quite handy to be able to reload an asset in multiple device targets. dmengine would have to bind to a dynamic port and in the editor it must be possible to select more than one device target.

Business need:
Indie developers. (LINK REMOVED)

```

**Comment by koenbollen** [comment]
Hey,
This is now one of my biggest time sinks. I try to work around it with bundling for once instance and then iterating with a normal build (ctrl+b), but that only works if the changes I'm testing are on only one side of the two running instances. And having to wait for bundling every time really slows me down.

Godot has this option:
![image](https://github.com/user-attachments/assets/9f9d6e6e-8d12-4c5a-8d66-8a982e0de9d5)
Something like that would be amazing.

Additionally it would be good if every instance has a unique identifier (e.g. a command-line argument stating which instance number it is). And it would help if the window location of each instance is not the same (maybe tiled across the monitor).

ref: My discord thread about this: https://discord.com/channels/250018174974689280/1260941258625650729

**Comment by britzl** [comment]
> Additionally it would be good if every instance has a unique identifier (e.g. a command-line argument stating which instance number it is)

What would this be used for? I'd like to understand what the unique id will be used for. There are probably a lot of different solutions to this.

> And it would help if the window location of each instance is not the same (maybe tiled across the monitor).

I agree that it would be nice, but I think this might be more complicated than expected.

**Comment by koenbollen** [comment]
> > Additionally it would be good if every instance has a unique identifier (e.g. a command-line argument stating which instance number it is)
> 
> What would this be used for? I'd like to understand what the unique id will be used for. There are probably a lot of different solutions to this.

An example: I have a multiplayer scenario I want to test (where one of 3 clients disconnects and reconnects). And I would then use this identifier to only have client#1 do the disconnecting and reconnecting.

Or just use the identifier to give each instance a different character in a multiplayer game or something.

Alternatively you can set a config option differ per instance.

> 
> > And it would help if the window location of each instance is not the same (maybe tiled across the monitor).
> 
> I agree that it would be nice, but I think this might be more complicated than expected.

I figured as much. Maybe this only works on the windows platform or something?

**Comment by AGulev** [comment]
By the way, @koenbollen, what OS do you use on a day-to-day basis for development?


I think that on the engine side, it's already possible using DefOS:

1. Pass parameter to the engine using
>./tmp/dynamo_home/bin/arm64-macos/dmengine --config=project.instance_index=1 ~/projects/InstanceTest/build/default/game.projectc

2.  get instance from Lua using
>local inst = sys.get_config_int("project.instance_index")

3. Based on index, apply changes using DefOS (pick monitor, position etc)

4. One-liner to run 4 indexes :
>for index in 1 2 3 4; do ./tmp/dynamo_home/bin/arm64-macos/dmengine --config=project.instance_index=$index ~/projects/InstanceTest/build/default/game.projectc & done


But I'm playing with implementation in the engine and the editor as well. Here I just added representation of the instance index in the window title (pay attention they have nums) + window position save only on Mac (it's OS functionality on Mac):

https://github.com/user-attachments/assets/9f8c1459-ea1c-40c7-b47a-8ec63467a1d8

I'll take a look into the editor's implementation as well

**Comment by AGulev** [comment]
I played with it a little bit more today and got it working, plus I added separate log.txt files for different issues.

https://github.com/user-attachments/assets/06ac924a-3cf8-4670-910d-dee00692dec9

It's not done yet. A few design decisions need to be made.

**Comment by koenbollen** [comment]
Looks really good, perfect! 👍 Is there a branch I can checkout to beta test/review this feature?
I'm using **Windows** as my main development OS.

**Comment by AGulev** [comment]
> I'm using **Windows** as my main development OS.

Here is a build where 4 instances hard-coded for now.


https://d.defold.com/archive/dev/d492b6aaf197a8b968963fe866b3611edeef7b65/dev/editor2/Defold-x86_64-win32.zip

What's done:
- Cmd + B launches a few instances (4 hardcoded at the moment).
- Editor keeps connection to the latest instance (console and as selected target).
- The instance index is in the app title.
- It's possible to get the instance index in runtime using `local inst = sys.get_config_int("project.instance_index")`.
- Each instance writes logs into its own file.
- Added the ability to pick a target that should be rebooted with new resources by cmd+B:

![CleanShot 2024-07-28 at 16 52 14@2x](https://github.com/user-attachments/assets/9a40213f-9b33-4677-8c60-936e6b56cd23)

What hasn't been done:
- An ability to change how many instances cmd+B should run.
- Testing on Windows and Linux.
- Maybe we need the ability to re-run all the instances somehow (I'm considering having a special target to do so, or something like that).

What isn't part of the issue:
- Save/load window position. On Mac, it is part of the OS API, so it works there out of the box, but it isn't something I'm implementing as part of this ticket for the other OSes.

Your feedback is welcome. Thank you.

**Comment by koenbollen** [comment]
Hey @AGulev, thanks for the build. Works great already, I'll be switching to this build next time I work on a multiplayer feature. I did test it already and played around with it some, and have some feedback (I tested on Windows 10):
1. First off, great feature for me to have. I'll be using it a lot and it will save me about a minute per iteration!! :fire:
2. The order of the window creation (i guess in time) is random, the first instance it not the first window created. See this screenshot (Windows window grouping):
![Screenshot 2024-07-29 112256](https://github.com/user-attachments/assets/d133238b-fc72-4ef0-b90b-45cc1a1850d2)
the order is always random. I click on these a bunch, and it would help my mental image of the windows if they are always in the same order (maybe have a 100ms delay between creation? or wait for the windows to be visible before creating the next).
3. Windows can't really identify the windows as they start (maybe because the window titles are not set directly but a bit later in the booting process). Which means I cannot use the [PowerToys' FancyZones](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones) feature to keep the windows in their own corners. FanzyZones allows Windows users more power with window management and has the setting to reposition new windows to their previous known positions (it would be incredible if this would work). I do not know how Windows identifies newly created windows (I assume by process and title?), maybe it works if the windows have a set title when they are created (not sure how that API works, and if that's possible to set at creation).
4. My (mid range) machine does feel it when I create 4 instances in one go, the 4 instances load a lot slower then when I only start one 😇 (this is expected, but I thought it would be worth to mention).
5. I dont use Esc to quit the game, but an idea I had anyway: Maybe Shift+Esc closes them all, or it's an option to have Esc close them all. I just use the Windows feature "Close all windows" in the taskbar.

**Comment by AGulev** [comment]
@koenbollen I've just submitted PR. It's not reviewed yet, so I'll change things there, but overall it's gonne be fmore or less like it is now. If you want, you can test it here: 
https://d.defold.com/archive/dev/06bcb030dfc4df8eaa0644b8231d093d5bc5b06e/dev/editor2/Defold-x86_64-win32.zip

Special thanks for your feedback. It helped me a lot!!

1. ❤️
2. I tried to fix it by adding a delay.
3. It's not something I control here. But we are moving to GLFW3 (it's not in this PR yet), so maybe it will help.
4. Yes, I'm not sure if I can do something with it, unfortunately.
5. I added an option in the editor to close all instances. For now, it's assigned to `Ctrl+J`, but it might be changed after review.

I made some changes to make it more convenient. You can read about all the changes in the PR https://github.com/defold/defold/pull/9256

**Comment by koenbollen** [comment]
Hey @AGulev,
Works great! I've been using this build for a while now (not working to much on multiplayer atm tho).

2. The delay doesn't seem to work. The order of windows is still a bit random.
5. Ctrl+J to close all works well. 👍
6. The new menu is not disabled while building:
![image](https://github.com/user-attachments/assets/09c2dd1e-a215-4d45-8a44-7eec8ffa7f1a)
   I can imagine this will cause bugs if users change the instance count mid build.
7. The naming could be a bit more clear I feel (for other users, I'm ok with this).
   - "Instance Count On Build" is not super clean, maybe "Number of instances to run..."?
   - "Close Engine" I can imagine this be confusing for new users. Is that closing Defold? I don't think many users know the 'engine' is started when you build and not the game. Maybe "Close all instances"?
   - Over all the Project menu feels like it's getting messy. Maybe the Close Engine item could be part of the submenu where you select the instance count:
```
**[Project]**
Build                         Ctrl+B
Rebuild
Multiple Instances ->
    Run 1 instance on build
  ✔ Run 2 instances on build
    Run 3 instances on build 
    Run 4 instances on build
    Close all instances       Ctrl+J
Bundle ->
    ...
Rebundle                      Ctrl+U
...
```
Making multiple instances one item, since it's only used by a subset of Defold users.

Thanks again, I'll be using this build until it releases in the next version!

**Comment by AGulev** [comment]
It's already available in beta with minor changes: https://forum.defold.com/t/defold-1-9-2-beta/77687/2
