### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [defold/defold#4810]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [dmGameSystem::AcquireResources function](https://github.com/defold/defold/blob/869a87718757bdb7bfd6ed078047fa7bfb451de9/engine/gamesys/src/gamesys/resources/res_textureset.cpp#L43)
- [dmPhysics::World3D class](https://github.com/defold/defold/blob/869a87718757bdb7bfd6ed078047fa7bfb451de9/engine/physics/src/physics/physics_3d.cpp#L124)

**Comment by eangelin** [comment]
Hi @elfring! Thanks for your report and attention to detail! We don't use exceptions in the engine and actually compile with exceptions disabled. We also try to keep the number of external dependencies as low as possible, even avoiding most of the standard library and containers. Can you spot a risk of memory leak in the cases above?

**Comment by elfring** [comment]
Yes (in principle).

Would you like to [follow known programming guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”")?

**Comment by JCash** [comment]
Well, we have a fairly small code base, and we have known code paths to the resource handling. The pointers also have clear ownership. And tbh, leaking memory is very rare, and usually very easy to find.
All in all, so we don't need or want any smart pointers. Sorry.

Also a reminder that we wish to keep the code size a small as possible, which is prohibits the use of smart pointers.
And, using std in the engine might affect the ABI, which in turn might affect the extension developers, which we don't want.

So, small and tiny, as few dependencies as possible, and we'll get a fast and small engine.

Here's a few lines detailing a bit further on how we think:
https://defold.com/manuals/extensions-best-practices/

We'll add similar info for the engine / editor itseld soon.

**Comment by elfring** [comment]
>Also a reminder that we wish to keep the code size a small as possible, which is prohibits the use of smart pointers.

I suggest to reconsider your conclusion.
* Can smart pointers be helpful for various use cases?
* Would you like to copy known functionality from other class libraries?

**Comment by paweljarosz** [comment]
> we wish to keep the code size a small as possible, which is prohibits the use of smart pointers.

I don't quite understand that point, the memory overhead of std::unique_ptr is zero, unless you are playing with deleter. Even shared_ptrs control block shouldn't add a lot of overhead for this project. If you don't want to include whole memory library, maybe a custom implementation of Unique_ptr could be possible?

> we have a fairly small code base, and we have known code paths to the resource handling. The pointers also have clear ownership

Well, it is perhaps true now, but since the code is available and you would like people to contribute to it, this is really important. People will try to update some part and could not bother about ownership, quality and leaks - they could make mistake, and smart pointers are to remove such possibilities - and will you catch it in as soon as in a Code Review?

**Comment by JCash** [comment]
1) With smart pointers, it's usually meant `std::shared_ptr` and `std::weak_ptr`.
There is a _lot_ of code involved with them, and there's also a mutex, which stalls the code until another has released the resource.

Here is an example comparing a raw pointer access to a weak_ptr access:
https://godbolt.org/z/QjiR9P

2) It must be true going forward too! We cannot allow contributors to "not bother". If that is the case, the reviews won't be accepted. In truth though, I don't see destruction of pointers as a problem, because it's not as hard as it's made out to be.
