### ISSUE TITLE
A discussion about sound

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#4837]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Defold's sound module never felt usable for me once going past 1 music track and some simple SFX. Here's a list of annoyances off the top of my mind:

  * Last time I checked loading a long music track causes it to load fully into memory, uncompressed PCM. I might be wrong, since this was a long time ago.
  * It's single-threaded and it stutters whenever the main thread is particularly busy.
  * It's impossible to play two sounds in sequence gapless (which would enable the user to create complex conditional loops, which is a must for adaptive music).
  * I can't do a low-pass. Basic DSP support on mixer groups would be very nice. Some dynamic EQ-ing can make things really immersive, for example.

**Describe the solution you'd like (REQUIRED):**
I have the following proposal and I volunteer my spare time towards implementing the following:

Update: Nevermind. I just read through the code and noticed that you're using OpenAL just as a sound output and you generate your own buffers. That's awesome! In that case, switching out OpenAL might not do much in terms of maintainability (might reduce some latency, though). I still stand on my proposal to try my hand at making this threaded.

I'll create separate issues for each of the above annoyances some time tomorrow.

~Let's get rid of OpenAL. I worked with it in the past and it's very limiting. Doing certain things (like streaming) is needlessly complicated, certain things are downright impossible (DSP, for example, unless you use an extension) and implementations are buggy as hell (I remember having issues with the iOS implementation, for example).~

~Instead, I say, looking at Defold's current feature set, it wouldn't be very hard to reimplement it by generating and filling our own sound buffers on a callback from the sound card. It's very easy to port to OS-specific APIs and it allows much more headroom for implementing new features going forward. I propose we use PortAudio on desktop systems and implement it using CoreAudio on iOS and Oboe on Android.~

And I can make it threaded simultaneously, while I'm at it.

**Describe alternatives you've considered (REQUIRED):**
FMOD, but it's not always free and it's a huge overkill library bigger than Defold's executable size by a good factor.

**Comment by subsoap** [comment]
The vast majority of users who want to make polished games do not need the features of FMOD. But they do need better audio than what is currently available. I would strongly vote for this.

Special considerations should still be taken for iOS and Android. I know @Lerg has done some work related to this in the past.

This proposal could have consideration be made to be compatible for an editor / bob feature down the road like texture profiles but for audio. That kind of system could let us define audio file compression per platform and make the audio types be converted during bundle time for whatever the target platform prefers as its native playback format.

**Comment by JCash** [comment]
Very nice proposal!

Regarding loading a sound fully into memory, I think there's something afoot. Since we memory map all sounds, there really shouldn't be a need to read all data at once. It should suffice to read little by little from the sound data. Something to investigate I think.

Regarding filters (low pass in this case), and adaptive music, I've been toying with the idea of some kind of sound extension which would let you supply new or altered sound data to the sound system on demand. So far, it's just an idea though.
Oh, and it should be able to use our buffer format.

**Comment by dapetcu21** [comment]
So, can I start work on a threading PR later this week / in the weekend?

**Comment by JCash** [comment]
Just to let you know, I've started with the threading part of the task.

**Comment by dapetcu21** [comment]
Awesome! I didn't get time to do this, sorry.

**Comment by subsoap** [comment]
What are the odds of getting threaded playback and true threaded loading? So we can dynamically load songs without that loading impact the main thread of the game too.

**Comment by JCash** [comment]
Well, first I need to understand what the issue is.

"threaded playback", not sure what that is, compared to playback on a separate thread?

As for memory consumption, I'll look into that too.
Currently, the dmSound::SetSoundData() makes a copy of the data, which I wouldn't have expected to be needed at all.
The resource should be valid when the sound data is valid, so it should be fine using the resource pointer straight up.

**Comment by JCash** [comment]
As for the last two points in this list, we need some ideas on how to do it.

>It's impossible to play two sounds in sequence gapless 

We (currently) pass messages to the sound component (comp_sound.cpp) and it uses polling to detect if a sound is done.
Now, with threading, the component and the actual sound will be even more out-of-sync, so we need a better way to get feedback. My best guess is to use a callback. Where should this callback call? (Probably) Not to Lua, since that lives on the main thread, and the call originates from the sound thread, and we want to supply it with a new sound name, so that it can play "gapless".

Or another idea, is to queue this info onto the currently playing `play_id`. E.g. `sound.queue("#nextsound", {prev_sound = play_id})`. If the sound exists, it adds the next sound to be played right after the previous one, achieving gapless playback. If the sound happened to _just_ finish (threaded playback), the next sound will be played asap (same as using `sound.play()`)



> I can't do a low-pass. Basic DSP support

Apart from what such an API actually needs (buffer size, cursor position?, etc), a big part of the problem is the data flow.
Currently, we fill 6 buffers à 768 frames, asap. So it plays ~6+ frames into the future, and I imagine that you'd like to get it a bit more tighter than that. E.g. playing an effect that reflects what happened in the game the same very frame.

Apart from allowing to change the number of buffers/frames, how to get this modified data has the same problems as the previous issue: we do the callback from the sound thread. Ideally, I'd like to be able to manipulate this buffer from Lua. But we can't, if we use the main Lua context. Perhaps we can use a special Sound Lua context? Making effects from Lua is perhaps not as desired as being able to queue the "next sound" for gapless playback. Problem is, this context would probably need to share some things with the main context, in order to know what sound to play next.
For effects though, I don't think it's _actually_ needed to manipulate it from Lua, and keeping a separate C api for sound effects is much simpler, and to the point. Which is what I think we should go for.

**Comment by dapetcu21** [comment]
> Or another idea, is to queue this info onto the currently playing play_id
Yes, this sounds like a really reasonable solution. The user should also, ideally, have a way to get the position of the playhead so that they can know when they're approaching the end and queue the next sound.

> and keeping a separate C api for sound effects is much simpler, and to the point
+1. Leave it to the native extension designer to implement DSP plugins and interact with Lua for changing effect settings and whatnot.

One thing I would add to the list is making sure we retain the current behaviour where if you start two sounds during the same frame they will play in sync with each other, matched sample-to-sample. This lets you mix multi-track adaptive music, so that you can, say, make the music more ominous by raising the volume of a strings track.

**Comment by JCash** [comment]
> The user should also, ideally, have a way to get the position of the playhead so that they can know when they're approaching the end and queue the next sound.

Yes, seems like a crucial feature

> making sure we retain the current behaviour where if you start two sounds during the same frame

I think we need to have a new function for this though, as the sound thread may start it's update/consume work at any point. (i.e. in between two calls to sound.play()). E.g. sound.play_sounds().

**Comment by subsoap** [comment]
About asset loading, if I load some big collection with the current async loading it has caused the game to hang for me at the point of loading in the past. As in, there is a noticeable hang. Unfortunately I do not have working older hardware anymore and my current setup this doesn't happen but I'm still concerned about it. We do have users with lower end hardware so when async audio playback is added we can send out tests to get user reports if there are any problems related to asset loading still.

What I am concerned about is if during playing a game while the game loads different songs (to minimize total memory use) there can be hangs in the game sim which are noticeable to the player since song swaps would happen during normal gameplay and not during menus. For people with great hardware, even with the current way Defold works with audio and loading they don't notice any issue, but for people with slower CPUs and older HDDs they notice it and it disrupts their play.
