### ISSUE TITLE
GLSL Optimizer

### ISSUE THREAD

**Issue by tomurtogu** [defold/defold#5034]
We are developing games for the mobile platform, so we use the GLES2 . I wonder if Defold has a GLSL optimizer like this: https://github.com/aras-p/glsl-optimizer, or do we have to optimize the shaders ourselves?

**Comment by JCash** [comment]
We currently transpile the shaders through SPIR-V, but I don't think it does any optimizations. 
Since we're moving towards a Vulkan pipeline (albeit with GLSL shaders for backwards-compatibility), we haven't looked into Aras' glsl-optimizer any further.

You should be able to run the tool yourself on your shader as a prebuild step.
[editor scripts](https://defold.com/manuals/editor-scripts/#lifecycle-hooks)

**Comment by aglitchman** [comment]
> We are developing games for the mobile platform, so we use the GLES2 .

If you're going to use a standard Defold sprite shader then you don't need a GLSL optimizer. It's already optimized.

**Comment by Jhonnyg** [comment]
We will do this by utilizing the spir-v toolchain by doing things the other way around - generate GLES2 code from spir-v shader code, which is ran through the spirv-optimizer toolchain.
