### ISSUE TITLE
Copied collision 3d box doesn't show properly in the editor

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#5049]
### Expected behaviour

- Create collision box in the game object
- copy it
- paste it to another object
- show all 3 dimention correct
Original box:
![2020-07-28_13-33-26](https://user-images.githubusercontent.com/842807/88640070-f5954280-d0d6-11ea-8cbd-9eccd88f521b.png)

### Actual behaviour

Shows flat "box", where D is 0 (only visual, it still correct in numbers and in runtime)
Copied box:
![2020-07-28_13-32-49](https://user-images.githubusercontent.com/842807/88640014-e1514580-d0d6-11ea-868e-736e0ef4bcd2.png)

### Steps to reproduce
Screencast is here:
https://yadi.sk/d/NaENdek6FQG_-Q
<hr/>

<table>
<tr><td>Build time</td><td>2020-07-25T06:13:26.934742</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a64a72ca0d10f1583edab5b4317499cdc8c64e5</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 442.23</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
From Mats: "It looks like the missing piece is some way of retaining connections to global nodes such as the project node when copy/pasting.

The way it works currently is that every connection that is put on the clipboard will be between the nodes in the copied graph fragment.

It looks like someone thought about this scenario, because you can supply a custom :serializer function when copying, and a custom :deserializer function when pasting in the graph. The comment mentions you can use it to do this very thing - connect stuff to external nodes.

The actual copy-paste functions from the editor are in outline/copy! and paste!, respectively. It might not be that difficult to wrap the default serializer/deserializer functions and tack on a connection, actually.

Like, add a list of external connections to the project node to the :serializer return value and add (g/connect) calls for them in the :deserializer.

**Comment by Dragosha** [comment]
Additional info:
if copy collisionobject with capsule shape and try to build the project then here is a build error:
`Capsule shapes are not supported in 2D physics`
Seems copied collision object the editor not only shows as 2d but marks as 2d?

**Comment by ufgo** [comment]
oh... same problem... i hope defold team will fix it

**Comment by vlaaad** [comment]
I'm working on it!

**Comment by vlaaad** [comment]
Fixed, please check for updates.

**Comment by d954mas** [comment]
Thanks,it worked👍👍👍
