### ISSUE TITLE
Dynamic Collection Loading

### ISSUE THREAD

**Issue by 3mic4nia** [defold/defold#5068]
Is your feature request related to a problem? Please describe (REQUIRED):
No, it isn't.

Describe the solution you'd like (REQUIRED):
It would be useful to have the ability to tell the engine which collection to load using a single command.

Describe alternatives you've considered (REQUIRED):
Dynamically add collections proxies and assign a collection to them.

**Comment by britzl** [comment]
Could you please elaborate on what you want? How are you loading your collections/levels now?

**Comment by 3mic4nia** [comment]
I currently use a main collection with several collection proxies

**Comment by britzl** [comment]
* Collections, and all other resources, must be referenced in the "scene graph" to be included in the game. This means that you must reference every collection either through a collection factory or a collection proxy (or the bootstrap/main collection). You already do this so that's not a problem, but your suggestion of passing a file path would not work based on the assumption that everything has to be referenced from the main collection or sub collection(s).

* If your problem is manually adding the collection proxies then I guess you could script this?

* Depending on the kind of game you have you may not need one collection per game? Perhaps the level could be defined in some data format and the from a single level.collection you would create the level based on the level definition?

* Or is your problem that you would like to simplify the actual .script code to load the levels?

**Comment by 3mic4nia** [comment]
Thank you for replying me,

Well, I thought that using a single command for loading a scene could be more straight forward, but obviously, I can script that.

P.S.
Sorry for opening this useless issue: I looked through the source code trying to figure out how to make this only then making this issue, sorry again.

**Comment by britzl** [comment]
No worries! I hope you figure out a solution that works for you!
