### ISSUE TITLE
Callback function in go.delete

### ISSUE THREAD

**Issue by Alfagun74** [defold/defold#5117]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm always frustrated when go.delete is async and i have no way to wait for its completion.

**Describe the solution you'd like (REQUIRED):**
I want a callback function similar to animations, that runs code upon the real-deletion.

**Describe alternatives you've considered (REQUIRED):**
You can wait exactly one frame and be sure the go. got deleted but thats not very practical.

**Comment by britzl** [comment]
So if you delete a game object in one frame it will live for the duration of that frame. This helps you avoid all sorts of problems and makes the game engine loop a lot simpler to reason about. At the end of the frame the game object will be deleted and all components will be finalised. This means for instance the final() lifecycle function will be called on any script.

You haven't really presented much of an actual example where this becomes a problem. In the Discourse chat you write "And because go.delete()= us async, 2 game objects coexist, which breaks my game logic". I'd like to learn more about what you mean by "breaks my game logic".

Something to look into is the use of Lua coroutines to make async code look synchronous. You can run code within a coroutine and pause the coroutine execution while waiting for some async process to finish. In the case of waiting to the next frame it can be achieved by waiting for a timer with delay set to 0 to trigger. An example of how this could look can be seen in this sequence.lua module which wraps a bunch of async functions into a convenient module for running things in sequence:

https://github.com/britzl/ludobits/blob/master/ludobits/m/sequence.lua

Example:

```
local sequence = require "ludibits.m.sequence"

sequence.run_once(function()
	go.delete()
	sequence.delay(0)
	factory.create(...)
end)
```

**Comment by Alfagun74** [comment]
>  I'd like to learn more about what you mean by "breaks my game logic".
Well basically there is a factory that spawns a new go upon deletion of an old one.
`lua
stuff = nil
stuff = factory.create(stuff)

function respawn()
 go.delete(stuff)
 stuff = factory.create(stuff)
end
`
At a specific moment of time both gameobjects (the old one and the new one) coexist for a single frame which is "what breaks my gamelogic". And because i can not wait for deletion i currently have to find solutions like the one frame thingy or disable the go with bools like Jerakin said.

**Comment by Alfagun74** [comment]
By the way thanks for the coroutine workaround but i got to admit the "wait one frame" thingy is a bit too hacky imo compared to a simple callback function.

**Comment by britzl** [comment]
Won't fix. Workaround:

```
go.delete()
timer.delay(0, false, function()
    -- next frame
end)
```

Could be made into a Lua utility function.
