### ISSUE TITLE
adding camera and testing

### ISSUE THREAD

**Issue by sliebor** [defold/defold#5142]
i tried adding camera to project and then start the project but some weird error about wifi related stuff apeared

**Comment by 8bitskull** [comment]
For future reference - there's not really such a thing as a "weird error". One of the most critical pieces of information when evaluating an issue like this is error messaging. So, the error might not make any sense to you, but it most likely makes sense to those responding to issues like this. This means you should share error messages even if they might seem confusing.

**Comment by britzl** [comment]
There is no actionable item in this bug report, just like @8bitskull said. We really need to know more about the problem. When you create an issue there is a template with a bunch of field you need to provide:

**Describe the bug (REQUIRED)**
A clear and concise description of what the bug is.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior (REQUIRED)**
A clear and concise description of what you expected to happen.

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]
 - Device: [e.g. iPhone6]

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**
If applicable, add screenshots to help explain your problem.

**Additional context (OPTIONAL):**
Add any other context about the problem here.

**Comment by britzl** [comment]
No more info provided. Closing.
