### ISSUE TITLE
Trying to open the new .bmp in the builtins on Windows freezes the editor + it's huge

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5231]
First if keeping the builtins size low is a goal then shipping a .bmp is a bad idea. It's 3MB!!!

It also seems to make the editor free on Windows if you try to open it from the editor.

If you want to include images in the builtins then you should ship versions of the Made with Defold logos too.

**Comment by britzl** [comment]
I wasn't aware that we had a .bmp image in builtins! I don't see it used anywhere either. @JCash do you recall why the images were added?

https://github.com/defold/defold/tree/dev/engine/engine/content/builtins/assets/images/logo

**Comment by britzl** [comment]
Btw, the .bmp file isn't really "new" as the title suggests. It's been in builtins for 6 months.

**Comment by JCash** [comment]
Some examplanations/thoughts:

* I don't like apps without a default logo :)
* Some platforms require .bmp. In this case it's Nintendo Switch
* I chose the blue logo since that's the log the editor uses (i.e. official/familiarity)
* The goal is to keep the download size low, not builtins.zip per se
* The size is `3147874` bytes uncompressed, and it deflates by `94%` into `185060` bytes.
* The difference in size for bob.jar is `185038` bytes

There are of course things we could do:
* Only bundle the icon in the Switch version of bob.jar
* Detect format, and convert from `.png` to `.bmp` at bundle time
* Change icon image to something that compresses better

I feel the bang-for-the-buck in this case is fairly low.
I believe there are other things we can pursue in order to further decrease the size of bob.jar/editor.
E.g. removing more functionality from the engine into extensions.
The code size (and debug symbols!) is by far the biggest component.
Although the biggest bulk comes from the editor itself.

**Comment by JCash** [comment]
> If you want to include images in the builtins then you should ship versions of the Made with Defold logos too.

Sure, this was a first step, and by no means the final inclusion of files into builtins.zip.
Feel free to make pull requests for other additions!

**Comment by britzl** [comment]
@subsoap: Now that we're talking about builtins content I'd like some feedback on this PR: https://github.com/defold/defold/issues/5137

**Comment by subsoap** [comment]
@britzl That does make sense. I'll suggest some assets for inclusion in the future.
