### ISSUE TITLE
Automatically install Android and iOS builds on devices

### ISSUE THREAD

**Issue by Lerg** [defold/defold#5392]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Other engines provide an option to automatically install the built APK or APP files on Android or iOS devices.
Such option would speed up development and make it easier overall.

**Describe the solution you'd like (REQUIRED):**
Add a checkbox such as "Install and run on device" when building for iOS or Android. A default connected device is fine, but a dropdown with the list of devices is welcome too.

**Describe alternatives you've considered (REQUIRED):**
There is no alternative.

**Additional context (OPTIONAL):**
Unity does it for Android. Solar2D does it for both Android and iOS.

**Comment by JCash** [comment]
I think this would be a good candidate for a "post bundle" event, that can invoke an editor script.

**Comment by britzl** [comment]
Pre-step: Are we allowed to redistribute the tools in bob?
Yes: Bundle tools and use them to install and launch game on device

No - Step 1: Detect Android SDK and Xcode command line tools and use them to install and launch game
No - Step 2: Trigger installer if tools are not installed

**Comment by vlaaad** [comment]
XCode command line tools are 700Mb. Solar2D [seems to be using](https://github.com/coronalabs/corona/blob/0e475c94440f3e2ce876df945dba0d16c6d3f9d6/platform/resources/ios_sendapp.sh#L128) the [ideviceinstaller](https://github.com/libimobiledevice/ideviceinstaller) executable for macOS installations though. Not sure if we can use it because the library uses GPL. It seems that Solar2D does not distribute it, but only checks if it exists and [provides install instructions](https://github.com/coronalabs/corona/blob/0e475c94440f3e2ce876df945dba0d16c6d3f9d6/platform/mac/TVOSAppBuildController.mm#LL1049C7-L1049C36).

adb is 13Mb though, and seems to be apache-licensed

**Comment by JCash** [comment]
> It seems that Solar2D does not distribute it, but only checks if it exists and [provides install instructions](https://github.com/coronalabs/corona/blob/0e475c94440f3e2ce876df945dba0d16c6d3f9d6/platform/mac/TVOSAppBuildController.mm#LL1049C7-L1049C36).

This sounds like something a post-bundle editor script could do :)

**Comment by vlaaad** [comment]
The plan:
- add new preferences:
  - Android installer path
  - Android installer args (should support substitutions like Code -> Open File preference)
  - iOS installer path
  - iOS installer args (should support substitutions like Code -> Open File preference)
- add heuristics for inferring Android and iOS installer paths (try different places for each desktop OS)
- add checkboxes to Android and iOS bundle dialogs: "install on device", disabled if the installer is neither explicit nor found. Provide some instructions/pointers about installing tools and/or specifying them in the preferences.
- run the installer if inferred or explicitly specified, and show the output in the editor console

**Comment by vlaaad** [comment]
Open question: what about `run` step after install?

**Comment by vlaaad** [comment]
Open question: what about multiple connected devices?
