### ISSUE TITLE
Cannot bundle for iOS on Linux

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5409]
**Describe the bug (REQUIRED)**
I'm trying to set up CI for a project and I decided to build iOS builds of the project on a Linux runner without code signing and then manually sign it myself before uploading it to the App Store (since macOS runners are really expensive, at least on GitHub Actions).

```
Error: Exception in thread "main" com.dynamo.bob.CompileExceptionError: /libexec/x86_64-linux/lipo could not be found locally, create an application manifest to build the engine remotely.
```

Unfortunately, it tries to lipo the binaries locally even if I give it a native extension manifest.

Fortunately, lipo is part of cctools, which Apple open-sourced. Here's a Linux port: https://github.com/tpoechtrager/cctools-port

Ideally, extender should lipo itself and bob should ship with prebuilt universal binaries (at least for the armv7+arm64 combination), but an intermediary solution would be to bundle the above-mentioned port with bob.jar in libexec.

I also tried compiling for just a single architecture and it seems to have used lipo regardless. Maybe the step should be skipped if there's only one arch? Update: I [made a PR](https://github.com/defold/defold/pull/5410) for this.

This will also be relevant for the Apple Silicon situation, btw.

**To Reproduce (REQUIRED)**
Build anything for iOS on Linux with Bob.

**Expected behavior (REQUIRED)**
I would get an unsigned ipa.

**Defold version (REQUIRED):**
  - Version: Latest alpha (d4a120ad797d85c105d100d36540e36bd2b6e985)

**Platforms (REQUIRED):**
 - Platforms: Github Actions ubuntu-latest

**Comment by JCash** [comment]
I've approved the PR for the single architecture fix.

As for the lipo'ing of the binaries on the extender, there's a bunch of stuff to do in order to make that work, and I'm not really sure what's the best way to solve that. For instance, our entire pipeline is setup for building each architecture on its own, and changing that for this case will introduce a lot of changes.

In my mind, I think we want to provide the lipo tool via bob (as we do with strip etc).
I have built those tools once on my home windows PC, but unfortunately that exe didn't run under my work windows pc. So more investigation is needed, although I'm certain it's possible. Then we can also get signing support.
