### ISSUE TITLE
On Windows, architecture-specific resources are bundled regardless of arch

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5448]
**Describe the bug (REQUIRED)**
If I create `x86_64-win32` and `x86-win32` directories in my `bundled_resources` directory, no matter if I bundle for 32 or 64-bits, files from both folders end up in the final build. If the same file appears in both dirs, the 32-bit one is bundled.

This [breaks FMOD on Windows](https://github.com/dapetcu21/defold-fmod/issues/26), but I can work around that by bundling both 32/64 bit dlls with different filenames.

**To Reproduce (REQUIRED)**
See above. I also included a minimal repro case project.

**Expected behavior (REQUIRED)**
Bundling for 32-bit should only bundle files in `x86-win32` and bundling for 64-bit should only bundle files in `x86_64-win32`.

**Defold version (REQUIRED):**
  - Version 1.2.177

**Platforms (REQUIRED):**
 - Platforms: Windows bundled from macOS

**Minimal repro case project (OPTIONAL):**
[win32-bundle-issue.zip](https://github.com/defold/defold/files/5765883/win32-bundle-issue.zip)

**Comment by subsoap** [comment]
Sanity testing on Windows editor bundling and can this report

![2021-01-04 10_01_48-win32-bundle-issue](https://user-images.githubusercontent.com/409170/103564731-e5e30c80-4e73-11eb-9c5f-a80bbc22b2ad.png)

Not sure if this is a regression. We only shipped 32bit versions of our Windows game which uses FMOD and it seems 32bit version overrides 64bit for the same file name even when selecting 64bit bundle.

**Comment by dapetcu21** [comment]
Definitely a regression. We only ship Interrogation as 64-bit and this would definitely have caused bug reports. Last released Interrogation builds are pretty old though.

**Comment by britzl** [comment]
I've done some investigation:

When bundling for Windows from the editor we have a dropdown called Architectures (32 and 64 bit) in the bundle dialog. The choice from the Architectures drop-down is forwarded to bob as Platform and not Architecture as one would have thought (ie equivalent to `java --jar --platform=x86-win32`)

Unless Architecture is specified as an argument bob will use both architectures (x86-win32 and x86_64-win32). This is the reason that both files are copied.

The same problem can be observed from the command line:

```
java -jar bob.jar --platform=x86-win32 bundle
```

This will bundle for 32bit but copy resources from both architectures. You need to provide both to get the expected behavior:

```
java -jar bob.jar --platform=x86-win32 --architecture=x86-win32 bundle
```

I've created a PR to fix the issue in the editor and I will probably also add a sanity check to bob with regard to platform and architecture options when bundling for Windows. You can for instance set x86-win32 as platform and x86_64-win32 as architecture.
