### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5454]
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

May need to switch to Python 3 or something else.

**Comment by subsoap** [comment]
https://docs.python.org/3/howto/pyporting.html

https://github.com/defold/defold/search?l=python&p=1

**Comment by JCash** [comment]
As long as there are easy ways to install it, I don't feel the need to update it.
Just because it's no longer supported doesn't mean it will suddenly break :)

I suspect switching from Python 2 to Python 3 might cause some issues with `waf` (our build system) since we're using a quite old version. And updating to a new version of `waf` might not be not trivial.

**Comment by subsoap** [comment]
If 2.7 target is kept the docs will need to be updated as they describe installing Python 2.7 in a way which will not be possible in the near future - I got the warning above when following the instructions.

**Comment by Jhonnyg** [comment]
Hey, we've started working on this in [issue-5454-migrate-to-python3](https://github.com/defold/defold/tree/issue-5454-migrate-to-python3)
