### ISSUE TITLE
Failed to download symbols when building HTML5 Application

### ISSUE THREAD

**Issue by wulaiyin789** [defold/defold#5546]
### Expected behaviour
Download and build the package for js-web version successfully

### Actual behaviour
Error Occurs:
`Status 404: Failed to download http://d.defold.com/archive/5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66/engine/wasm-web/ `

### Steps to reproduce
Internet-Connected, no VPN is using

1. Go to 'Bundle' and choose 'HTML5 Application'
2. Click 'Create Bundle'
3. Wait until 'Downloading symbols'
4. Error Occurs

I was successfully built a package this afternoon until I updated a new Defold engine, then it failed. Currently, I still have this error.
Please correct me if I'm wrong. Thank you.

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-08T09:09:39.603768</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9892f06543413f700997f15be240cd8078ba4803</td></tr>
<tr><td>Defold engine sha</td><td>5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66</td></tr>
<tr><td>Defold version</td><td>1.2.179</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.8281</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Peter, could you please try to uncheck "Generate debug symbols" in the bundle dialog?

**Comment by wulaiyin789** [comment]
It's working again! Thanks so much!

**Comment by britzl** [comment]
We debug symbols can be used when debugging engine crashes. Previously we only downloaded debug symbols when building a custom engine (ie an engine with additional native code from extensions).

For "vanilla" builds (ie with no additional native code) the user had to download the symbols from our download page at d.defold.com (*.dSYM.zip for macOS, *.pdb for Windows, *.js.symbols for html5 etc).

In the latest release of Defold we changed so that the symbols are downloaded automatically also for "vanilla" builds, but there was a problem when downloading symbols for WASM builds (WebAssembly builds for HTML5).
