### ISSUE TITLE
RGBA 16bpp quality regression

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5678]
**Describe the bug (REQUIRED)**
RGBA 16bpp images are dithered with different algorithm in 1.2.180. Overall quality is lower than before.

**To Reproduce (REQUIRED)**
Look at two demos:
* [**Web build - Defold 1.2.180**](https://aglitchman.github.io/defold-basis-quality-test/180/index.html)
* [**Web build - Defold 1.2.179**](https://aglitchman.github.io/defold-basis-quality-test/179/index.html)

**Expected behavior (REQUIRED)**
"RGBA 16bpp" images should be dithered with the same algo as before.

**Defold version (REQUIRED):**
  - Version 1.2.180

**Minimal repro case project (OPTIONAL):**
https://github.com/aglitchman/defold-basis-quality-test

**Comment by Morgerion** [comment]
This is a real problem as we have a large number of graphics in 16 bit. Other formats are not suitable because there is no alpha, and the RGBA32 format still takes up too much space (twice as much as 16 bit).
When it comes to 8K atlases, this is important!

![Скриншот 2021-03-23 12 46 29](https://user-images.githubusercontent.com/7888071/112137718-a52ca100-8be1-11eb-9869-95871f488b3c.png)
![Скриншот 2021-03-23 13 54 47](https://user-images.githubusercontent.com/7888071/112137721-a5c53780-8be1-11eb-97c8-6eacc0218caa.png)
![Скриншот 2021-03-23 13 56 43](https://user-images.githubusercontent.com/7888071/112137722-a65dce00-8be1-11eb-8d31-c4e39bd272ac.png)

**Comment by JCash** [comment]
I agree, and I'll look into it now.

**Comment by JCash** [comment]
The biggest issue was that I had completely overlooked the dithering, and hadn't replaced it with something similar.
The original lib we used was PVRTexLib, which always was a pain to maintain for all our platforms, and it had served its purpose since it wasn't updated to produce any modern formats anymore. Only use case now was to produce dithered 16 bit images.

Here we implement the Interleaved gradient noise to produce the dithering. 
Only thing is that I'm perhaps not completely satisfied with the result for the alpha channel in the "circle image".
But if we figure out which dithering algorithm we wish to replace with, it shouldn't be very hard to do.
(see [texc_private.cpp](https://github.com/defold/defold/pull/5692/files#diff-6f654e31a85332b6a37de362a66abc866ae57f057dc4550c0675bbf6222c24b9))

Reading materials for the interested:
* https://en.wikipedia.org/wiki/Ordered_dithering (note used since it produced subpar results)
* https://bartwronski.com/2016/10/30/dithering-part-three-real-world-2d-quantization-dithering/
* https://blog.demofox.org/2017/10/31/animating-noise-for-integration-over-time/
* http://loopit.dk/banding_in_games.pdf
* https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc2016/Presentations/Gjoel_Svendsen_Rendering_of_Inside.pdf

Shadertoy:
* https://www.shadertoy.com/view/MslGR8

Testbed:
* https://github.com/JCash/dither

Comparisons:

The result is a tad different, both 179 and 181beta produces the same type of banding, just in slightly different places.
And the 179 version has slightly more banding (e.g. in the logo images). But I think they're more or less the same.

179
<img width="635" alt="image16bpp-179-00" src="https://user-images.githubusercontent.com/1349334/112511307-976a4d80-8d92-11eb-80fe-d2b20abd9b08.png">

180
<img width="635" alt="image16bpp-180-00" src="https://user-images.githubusercontent.com/1349334/112511330-9c2f0180-8d92-11eb-82c7-2233cda1bd06.png">

181 beta
<img width="639" alt="image16bpp-beta-fix-00" src="https://user-images.githubusercontent.com/1349334/112511369-a3560f80-8d92-11eb-9016-71ba4575fb17.png">


Here the alpha banding artifacts are slightly more pronounced in the 181beta I think.
I don't particularly like the 179 version either, but I think it might be slightly "smoother"

179
<img width="637" alt="image16bpp-179-01" src="https://user-images.githubusercontent.com/1349334/112511705-f62fc700-8d92-11eb-921a-45529cb33a28.png">

180
<img width="637" alt="image16bpp-180-01" src="https://user-images.githubusercontent.com/1349334/112511723-faf47b00-8d92-11eb-8977-9552340c443b.png">

181 beta
<img width="639" alt="image16bpp-beta-fix-01" src="https://user-images.githubusercontent.com/1349334/112511738-fdef6b80-8d92-11eb-99d7-8d7d903077c6.png">


In any case, this is ready to go into the beta, as a first fix (since we didn't have any dithering at all!).

If necessary, let's continue the discussion here to figure out what needs to be improved as a step 2.

**Comment by Morgerion** [comment]
That's a great solution. I am completely satisfied.
