### ISSUE TITLE
Default mapping for not-listed gamepads

### ISSUE THREAD

**Issue by Lampogolovii** [defold/defold#5895]
I have a problem with [Sberbox TV](https://sberdevices.ru/sberbox/) device (based on Android).
There is an app for this TV-box with "virtual" gamepad.
It connects into Android system as regular gamepad. The problem, that the name of this virtual gamepad is "virtual_gamepad_83675" where the number "83675" is an ID of my account.
So there is no way to list all such names in default.gamepads file.

Another situation: there are a lot of cheap gamepads which imitate more famous ones (like XBox or PS).
These cheap models have the same mapping, but it is very hard to list them.

I have several ideas:

1. Add regular expressions support to gamepads list:
So I could use virtual_gamepad_*
Or DefenderMaster*

2. Connect any gamepad and notify a game about this (not only listed ones). So I could use my own mapping in the game.

**Comment by britzl** [comment]
> 1. Add regular expressions support to gamepads list:
>   So I could use virtual_gamepad_*
>   Or DefenderMaster*

This would be relatively easy if we only allow the wildcard at the end like that. It would basically mean that instead of a "string compare" we do a "string begins with" check. It would become much more complicated if we allowed "Xbox * Controller".

The solution with a wildcard symbol at the end would work in your specific case with "virtual_gamepad_*" for the Sberbox virtual controller. But would it be useful in other situations as well? Do we have any examples of controllers such as your other example with "DefenderMaster*" where many different types of controllers are named "DefenderMaster*" and have their buttons set up in exactly the same way?

> 2. Connect any gamepad and notify a game about this (not only listed ones). So I could use my own mapping in the game.

What do you mean when you say "so I could use my own mapping in the game"? Letting the player do the mapping in some kind of gamepad configuration screen? (Press left stick up. Press left stick down. and so on?).

**Comment by britzl** [comment]
Detected gamepads are currently stored as dmHashTable32 here:

https://github.com/defold/defold/blob/dev/engine/input/src/input_private.h#L138

And the check is made here:

https://github.com/defold/defold/blob/dev/engine/input/src/input.cpp#L120

We're currently matching hashes so we need to rethink how we store and search for gamepad names if we add support for wildcards.
