### ISSUE TITLE
[Linux] Toggle comment shortcut does not work

### ISSUE THREAD

**Issue by svprdga** [defold/defold#5959]
**Describe the bug (REQUIRED)**
The toggle comment shortcut `Ctrl+/` has no effect in the code editor.

**To Reproduce (REQUIRED)**
1. Create a Defold project in Linux
2. Create a script
3. Position the cursor in any line of code, try to comment it by pressing the shortcut `Ctrl+/`

**Expected behavior (REQUIRED)**
The current line is automatically commented, just the same effect that doing _Edit > Toggle Comment_

**Actual result**
There is no effect in the code editor when the shortcut is pressed.

**Defold version (REQUIRED):**
  - Version 1.2.184

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Linux Mint 20.1 Cinnamon

**Workaround (OPTIONAL):**
The workaround can be to create the comment `--` by hand, or by using _Edit > Toggle Comment_

**Comment by britzl** [comment]
Does it work if you change keyboard shortcut? https://defold.com/manuals/editor/#customizing-shortcuts

Also perhaps related: https://github.com/defold/defold/issues/5047

**Comment by svprdga** [comment]
@britzl no, does not work either, although I don't know if I have changed the shortcut correctly, I haven't had any error so I guess that I have done it well.

**Comment by beldenfox** [comment]
@svprdga What keyboard layout/language are you using? This may not be related to Linux but to the layout of the keyboard.

The shortcut is defined as Ctrl+Slash which means it will only work on keyboard layouts where the slash character can be generated without holding down the Shift key. To work reliably all punctuation-based shortcuts should be specified using syntax like this: Ctrl+'/'.

(In JavaFX Ctrl+Slash is a KeyCodeCombination and Ctrl+'/' is a KeyCharacterCombination and they're handled differently. There's almost no JavaFX documentation describing the difference or giving developers guidance on when to use one versus the other.)

**Comment by beldenfox** [comment]
Sigh. It is true that the shortcut should be specified as Ctrl+'/' instead of Ctrl+Slash but that won't help, the Linux implementation of KeyCharacterCombination matching in JavaFX is broken. I'll look into entering a JDK bug.

**Comment by svprdga** [comment]
Hi @beldenfox , I have a spanish keyboard, and my OS is configured in english, with spanish input. We have the `/` character in the keyboard, accessible without pressing shift nor alt. I also use this shortcut in many other editors to toggle line comment without issues.

**Comment by beldenfox** [comment]
For completeness I'll run down all of the ways of binding the slash key in JavaFX. You can add all of them to your custom shortcut file and see if any of them work.

This is the correct form and is supposed to work to bind the slash key on the main keyboard on all platforms and languages. Due to bugs in JavaFX it doesn't work reliably on Mac and Linux.

`["Ctrl+'/'" :toggle-comment]`

The following will only work for a slash key if it is on the main keyboard and can be accessed without using Shift or any other modifier.

`["Ctrl+Slash" :toggle-comment]`

This will capture the slash key on the numeric keypad.

`["Ctrl+Divide" :toggle-comment]`

**Comment by svprdga** [comment]
Thank you, `["Ctrl+Divide" :toggle-comment]` is what I was looking for.

**Comment by britzl** [comment]
@beldenfox is this information about the various alternatives for keynames available in some JavaFX documentation somewhere?

**Comment by beldenfox** [comment]
@britzl I haven't found any helpful documentation on this. The page for the KeyCode class lists all of the key codes. The documentation for KeyCodeCombination (`"Ctrl+Slash"`) is wrong and page for KeyCharacterCombination (`"Ctrl+'/'"`) is unhelpful.
I've got a PR pending to fix KeyCodeCombinations on the Mac and another one in the wings for KeyCharacterCombinations. I was planning to update the documentation after those were reviewed.

**Comment by britzl** [comment]
> I've got a PR pending to fix KeyCodeCombinations on the Mac and another one in the wings for KeyCharacterCombinations. I was planning to update the documentation after those were reviewed.

Oh, this sounds promising! How far from creating a PR are you?

**Comment by beldenfox** [comment]
@britzl I submitted the Mac PR (openjdk/jfx#425) back in March. I added some more comments over in #5047.

This bug is Linux specific. I don't think there's an existing JDK bug for it but will look again.

**Comment by beldenfox** [comment]
The pull request to fix this bug is openjdk/jfx#635.

**Comment by JCash** [comment]
I also have this behavior on macOS, where I cannot press <kbd>CMD+SHIFT+7</kbd> which is the actual key binding to do <kbd>CMD+/</kbd> on a Macbook.

**Comment by beldenfox** [comment]
@JCash On the Mac you're dealing with a different collection of bugs. The current binding definition is `Meta+Slash` which matches against the SLASH KeyCode. This will always be the key on the main keyboard that generates a slash when pressed with no modifiers. Swedish keyboards don't have any such key so `Meta+Slash` should never work. However due to a bug on Mac KeyCodes are always assigned as if the keyboard was English QWERTY where SLASH is the key just to the left of the right Shift key. That bug will be fixed in the next JavaFX release.

The binding definition should be `Meta+'/'` which should match any key that can generate a slash character, including the 7 key on a Swedish keyboard. And the binding should work if you don't press Shift. In theory you just need to change the binding to `Meta+'/'` and invoke it using `Cmd+7`. But due to an even odder bug the system won't figure out that the key can generate a slash until you type one. So change the binding to `Meta+'/'`, type `Shift+7` so JavaFX knows that the key can generate a slash character, and from then on out `Cmd+7` should work for you.
