### ISSUE TITLE
If component changes blend mode, the following predicate use this blend mode as well

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6179]
**Describe the bug (REQUIRED)**
Some components have its own blend mode settings (for example particle_fx, sprite, label) but the other components don't (mesh, model). As result, changing of the blend mode in component that supports this option may affect component that doesn't support this option.
For example if game draws particle with blend mode multiply and then a predicate with 3D model, then this 3D model will use multiply blend mode as well.

**To Reproduce (REQUIRED)**
1. Create a predicate for mesh or model component
2. Draw it after particle in render_script
3. Add a particle fx with `multiply` blend mode
4. Add mesh or model to the scene
5. Run game.
6. Model or mesh will have the same `multiply` mode as particle has

**Expected behavior (REQUIRED)**
Model should have it's own blend mode or use blend mode was used before rendering of particlefx predicate.

**Defold version (REQUIRED):**
  - 1.2.*

**Platforms (REQUIRED):**
 - Platforms: All the platforms
 - OS: *
 - Device: *

**Minimal repro case project (OPTIONAL):**
[Defold-Animated-3D-Example-main.zip](https://github.com/defold/defold/files/7530454/Defold-Animated-3D-Example-main.zip)

Remove label
and
Remove particle (or remove `particlefx.play()`) logic
or uncomment 
>render.set_blend_func(render.BLEND_SRC_ALPHA, render.BLEND_ONE_MINUS_SRC_ALPHA)
in `main.render_script`

**Workaround (OPTIONAL):**
Use 
>render.set_blend_func(render.BLEND_SRC_ALPHA, render.BLEND_ONE_MINUS_SRC_ALPHA)
in render script before rendering models and meshes predicate

**Screenshots (OPTIONAL):**

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2209596/141535442-30128b49-e7b2-4d77-9db7-1f2efdb78422.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/2209596/141535476-e60c763f-ed22-4068-b782-07b49d6ed1ab.png">

**Comment by AGulev** [comment]
https://forum.defold.com/t/texture-alpha-channel-bug-when-there-is-a-label-around/56789/11?u=agulev

**Comment by JCash** [comment]
> Model or mesh will have the same multiply mode as particle has

To clarify, it's the responsibility of each component to setup the states that it needs (in this case blend mode)

**Comment by Dragosha** [comment]
It's my case. I can not blend meshes and sprites in one render.draw predicat, because if there is sprite with add blending mode (fire) meshes after it will inherit blending mode.
![2021-12-16_21-18-58](https://user-images.githubusercontent.com/842807/146409740-8f659ff3-a2f1-4500-9c0d-4fbb0e3e590a.png)

**Comment by otsakir** [comment]
> > Model or mesh will have the same multiply mode as particle has
> 
> To clarify, it's the responsibility of each component to setup the states that it needs (in this case blend mode)

So @JCash , is this about setting blend mode to a default value before a model is rendered ? 

Probably, update the RenderObject in comp_model.cpp. I see that the rest of the renderable types of components do it in the respective files like comp_particlefx.cpp, comp_sprite.cpp etc.

**Comment by JCash** [comment]
> is this about setting blend mode to a default value before a model is rendered ?

Yes, each thing that want to render needs to make sure it set the state it wants.

**Comment by otsakir** [comment]
Besides `model` and `mesh`, are there any other components that need to be patched ? It seems to me that the rest are either not involved in rendering or already set blend function.

**Comment by AGulev** [comment]
> https://forum.defold.com/t/texture-alpha-channel-bug-when-there-is-a-label-around/56789/11?u=agulev

yes, also labels (maybe something else, but I'm not sure)

**Comment by britzl** [comment]
I was only aware of `model` and `mesh` but apparently also `label` is affected. Let's start there!

**Comment by otsakir** [comment]
About label component, i'm wondering what is the case there. There _is_ a `Blend mode` setting at least in the editor. 

hmm...

**Comment by AGulev** [comment]
> About label component, i'm wondering what is the case there. There _is_ a `Blend mode` setting at least in the editor.

now, when I think about (and read the forum post one more time) i understand that `label` was affected by mesh, but doesn't have such problem itself. So, I'm wrong here, ppbly problem is in `model` and `mesh`.

**Comment by otsakir** [comment]
I see...

Label rendering seems to set blend mode in the code properly. Same as particlefx or other components do. So, if a mesh/model were rendered afterwards, it would get affected by label (not the other way around).

**Comment by otsakir** [comment]
@JCash , does it make any sense to auto-test this fix? That is, test whether blend mode is indeed set to default value for model/mesh component ?

**Comment by AGulev** [comment]
> I see...
> 
> Label rendering seems to set blend mode in the code properly. Same as particlefx or other components do. So, if a mesh/model were rendered afterwards, it would get affected by label (not the other way around).

I read one more time what I wrote, and yes I means vice versa. Mesh affected by label. You are right.
Here is explanation of the issue and repo case project https://forum.defold.com/t/texture-alpha-channel-bug-when-there-is-a-label-around/56789?u=agulev

**Comment by JCash** [comment]
We've now realized that my suggested solution of letting each component set the blend mode that it wants/needs, will interfere with the mechanics of `render.set_default_blend_func()`.

Any `RenderObject` instance withe (optional) blend state set, will override the currently set blend state.
Thus, the current implementation suggests that the `render.set_default_blend_func()` is like a default blend state.

If the component _always_ sets the blend function (E.g. Sprites!), the function `render.set_default_blend_func()` loses it's usefulness.

I (currently) see two solutions:
* Add a new blend state for the components BLEND_STATE_DEFAULT, so that they may be overridden.
* Make the `render.set_default_blend_func()` actually override the set blend state.

The qeustion is, what are our users use cases, and what do we want in order to support that?

NOTE1: We also should think about its current use with respect to backwards compatibility.

NOTE2: It should be noted that the blend state is probably not the only state flag that might be affect by similar implementations.

**Comment by JCash** [comment]
I think the current discussed idea is:
* Add options table to "render.draw(predicates, [constants], [options])", where the options table can hold an overriding "blend_mode" setting.
* Deprecate the "render.set_blend_mode()", as it's not likely to function the way the users might think

**Comment by Jhonnyg** [comment]
Fixed by #6968
