### ISSUE TITLE
Crash when I press F5 to launch the game

### ISSUE THREAD

**Issue by TwillightDaamenrung** [defold/defold#6297]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-12-16T14:45:11.955824</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"204e97c24c5642c2ad73f6d0ff03b14b"'>204e97c24c5642c2ad73f6d0ff03b14b</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics (ILK)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-26-generic</td></tr>
<table>

**Comment by britzl** [comment]
It seems like there's an issue when connecting the debugger:

```
editor.debugging.mobdebug$connect_BANG_$fn__43260.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:339)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

Does this happen all the time?

I assume it works ok when you do Project->Build?

**Comment by coderm4ster** [comment]
For me, this exception occurs when I select a different target device than "New Local Engine". For example, I build a debug app (debuggable, debug variant) for android and then install it on the device. I then launch the app on the device, select the device as the destination in the editor, and then Start / Attach (F5) from the menu. An exception will occur after a while:

```
clojure.lang.ExceptionInfo: Failed to connect to debugger on 192.168.1.182:8172
        at editor.debugging.mobdebug$connect_BANG_$fn__43084.invoke(mobdebug.clj:339)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is probably because the debug app does not start the debugger server. If I select Project->Build first, it will transfer the built content to the debug app running on the device and the game will restart. Then the Start / Attach will cause the debugger to connect properly.

**Comment by britzl** [comment]
I'm unable to reproduce this, at least on macOS. I can connect the debugger over wifi to a running Android app. The editor does however freeze on me when trying to connect over USB with USB Tethering enabled and HORNDIS driver running. I think it is HORNDIS to blame.

How are you connecting to the Android device? Wifi or cable?

**Comment by coderm4ster** [comment]
I'm testing it on Windows 10. I checked it and the same error on both (usb cable, wifi) connections.

It can be retrieved in two steps:
1. Launch the debug version of the application on your Android target device (Debuggable flag is also enabled in the Android settings of the project)
2. Select Debug -> Start/Attach

After about 1 minute, the error will appear.

**Comment by coderm4ster** [comment]
I investigated this problem. Bob does not building the scripts needed to start debugging into the debug version of the game. I see the engine read the "bootstrap.debug_init_script" configuration value from the game project file.

https://github.com/defold/defold/blob/137535b3b48af694f1f70d14b47cdda3d9aacc4b/engine/engine/src/engine.cpp#L1118

I tried to write this key to the project file with the value that the editor uses during the build. The following error will appear in the editor during bundling:

![image](https://user-images.githubusercontent.com/14206860/150873872-bfeb8c0c-c296-4aa4-9c19-55c5adbf3d3d.png)

After a little searching, I found that Bob sets this configuration value to null:

https://github.com/defold/defold/blob/137535b3b48af694f1f70d14b47cdda3d9aacc4b/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameProjectBuilder.java#L385

So, since the debugger scripts is not included in the app and thus not started, the editor will not be able to connect after pressing F5.

**Comment by britzl** [comment]
> It can be retrieved in three steps:
> 
> 1. Launch the debug version of the application on your Android target device (Debuggable flag is also enabled in the Android settings of the project)
> 2. Select Project -> Target -> Some Android target device
> 3. Select Debug -> Start/Attach
> 
> After about 1 minute, the error will appear.

Brilliant. I can reproduce this. So this scenario fails:

- Bundle debug version of your app
- Start it
- Do Project->Target->Your Running App
- Select Debug->Start/Attach
- Nothing happens and after a while a "Timeout connecting to debugger"

This works:

- Bundle debug version of your app
- Start it
- Project->Target->Your Running App
- Build (the mobdebug files now get copied/streamed to the running app)
- Select Debug->Start/Attach
- The debugger is now connected

Notice the extra Build step which copies the mobdebug files.

**Comment by coderm4ster** [comment]
Yes, that's right. My last comment also points out why the mobdebug in builtins is not called.

If I run the project locally with F5 only (no build), it will run without error, the debugger will connect. I would expect this to work for a remote debug as well.

This behavior affects whether I can put a breakpoint at the start of the program. Currently, I can only attach (not start) to remote debugging, so startup events can only be debugged with timing tricks.
