### ISSUE TITLE
[Mobile platform] Add possibility to update native extension when application is in background

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#6336]
**Is your feature request related to a problem? Please describe (REQUIRED):**
[Mobile platforms] In some cases it would be good to run game loop when application is in background state. For example, we had some HTTP request, which we will send when application goes in background and we want to get request response.

**Describe the solution you'd like (REQUIRED):**
Add possibility to call Update in extensions when application is in background. And add possibility to run some part of game loop (message dispatching).

**Describe alternatives you've considered (REQUIRED):**
Reimplement functionality in platform-specific way (for example, use third-party libraries for doing HTTP request without Lua callback calling because we cannot synchronize data between game thread without calling Update) 

**Additional context (OPTIONAL):**
It request connected to implementation for mobile platform because Defold has special setting https://defold.com/manuals/project-settings/#run-while-iconified

**Comment by AGulev** [comment]
I think you are talking about this one? https://github.com/defold/extension-webview/issues/26

**Comment by ekharkunov-ms** [comment]
Yes, It's similar request.

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/6174

**Comment by AGulev** [comment]
1.2.174 works fine but doesn't work in 1.2.175

the reason is in one of the fixes 

e41438cca Merge pull request #5328 from defold/issue-5279-android-surface-create-issue
f50997390 Issue 5279: Handle case of creating a gl surface when window isn't valid
df240da76 Merge pull request #5326 from defold/issue-5279-android-detect-bad-surface
7e9b035d8 Issue 5279: Detect when the window surface it taken down on Android
2bb8f5e8c Merge pull request #5251 from defold/issue-5249-android-exit
