### ISSUE TITLE
Build Errors log isn't as informative as log in bob.jar 

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6402]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Sometimes Build Errors log isn't as informative as log in bob.jar. 

**Describe the solution you'd like (REQUIRED):**
It would be nice to see the reason of the build error in the editor or see the full log as when building using bob.jar.

**Describe alternatives you've considered (REQUIRED):**
Check logs from the extender or build with bob.jar and check what's wrong

**Comment by vlaaad** [comment]
@ekharkunov-ms is it still relevant now that #6408 is done? The changes in the solution to that issue are:
- All build engine errors are now shown in the Build Errors view. Previously, some exceptions that occurred during the engine build process were silently ignored.
- Files with invalid content are properly displayed in the Build Errors view. Previously, invalid files were displayed as "Unknown source" instead of a file path.
- Verbose bob log is now shown when bundling in the console view.

**Comment by ekharkunov-ms** [comment]
@vlaaad  I guess changes from #6408 would be enough.

**Comment by vlaaad** [comment]
Okay, closing then 👍
