### ISSUE TITLE
Do not put default protobuf values in the resource files.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6410]
**Is your feature request related to a problem? Please describe (REQUIRED):**

For now all the game resources contains both default and custom values in resources (collection, go etc)
It's not necessary to have it in files because in protobuf default values specified in `proto` files.

That would make format clearer and resources smaller in repo. Also it will simplify using of external editors that create the output files in Defold proto format.

**Comment by matgis** [comment]
Since 1.4.1 you have the option to mark certain project directories as non-editable. We recommend you do that for files that are generated by external tools. It will exclude these files from the save system, so it no longer becomes necessary to match the file format of the editor exactly.

It might still be beneficial to strip out the defaults from the saved files for the other reasons you stated, though.
