### ISSUE TITLE
Save dynamic properties for gui objects if layouts were changed

### ISSUE THREAD

**Issue by kornyushin** [defold/defold#6442]
When developing an HTML5 application, it is often necessary to support two layouts , one for desktop (landscape) the second for mobile (portrait)
if some gui elements change dynamically (for example, text or coordinates), then when the device is rotated, all properties  are reset to the default ones that were set in layouts 

Solution: Need save these properties and restore it, when layouts changed

**Comment by AGulev** [comment]
@britzl 
is it something we gonna implement? I mean, do we really want to track what user has changed in the Gui from code, what changed because of layout and then restore it? 

I cover it with my GUI lib for example. I think if we will cover it in the engine it will be a source of issues because only user knows how he wants his GUI to behave.

**Comment by britzl** [comment]
I agree. I would track this from a library built on top of the gui.* functions and let that library handle it. Let's close this.
