### ISSUE TITLE
HTML5 progress bar is not accurate

### ISSUE THREAD

**Issue by d954mas** [defold/defold#6563]
**Describe the bug (REQUIRED)**
Web. Progress bar show percentage
-start from 50
-then return to 40
-then load from 50-100

**To Reproduce (REQUIRED)**
Make web build.
Show percent of loading(or look at progress bar)

**Expected behavior (REQUIRED)**
Progress bar go from 0-100

**Defold version (REQUIRED):**
  - Version 1.3.0

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Windows 10 (firefox, chrome)

https://user-images.githubusercontent.com/2655263/165980108-95738858-0111-4eb0-9e1f-e4a53948118b.mp4
![2022-04-29_18-45-33](https://user-images.githubusercontent.com/2655263/165980131-0c4ea726-6a1a-4e91-94cc-a2ecf0a0420e.png)

**Comment by aglitchman** [comment]
> * Version 1.3.0

Have you tried to disable Wasm Streaming? i.e. by adding `EngineLoader.stream_wasm = false;` into your `.html` file.

**Comment by d954mas** [comment]
With ```EngineLoader.stream_wasm = false;```
progress bar is correct

**Comment by britzl** [comment]
Note: From 1.3.1 the WASM streaming is turned off as default and it is available as an option in game.project in the HTML5 section.

But regardless of that there's an issue with the progress bar calculation in dmLoader.js that we need to look into when was streaming is enabled.

**Comment by britzl** [comment]
The problem is that there's now out-of-the-box way to get the wasm streaming progress and instead we simply ignore the progressbar:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js#L136-L148

The proper solution seems to be to implement a custom ReadableStream and get progress from it. See:

https://stackoverflow.com/questions/65491241/get-webassembly-instantiatestreaming-progress

We're open for a PR to dmLoader.js!
