### ISSUE TITLE
gui.set_texture() is not automatically triggering gui.play_flipbook()

### ISSUE THREAD

**Issue by totebo** [defold/defold#6573]
**Describe the bug (REQUIRED)**
gui.set_texture() should trigger gui.play_flipbook() if the animation ids are the same, but this is not happening.

**To Reproduce (REQUIRED)**
```
local node = gui.get_node("box")
gui.set_texture(node, "test2")
```

**Expected behavior (REQUIRED)**
The texture should change and the node should be resized to the correct dimensions. 

**Defold version (REQUIRED):**
1.3.2

**Platforms (REQUIRED):**
macOS

**Minimal repro case project (OPTIONAL):**
[get_flipbook.zip](https://github.com/defold/defold/files/8618670/get_flipbook.zip)

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
Call gui.get_flipbook() before the set_texture() call, and gui.play_flipbook() after.

Forum post: https://forum.defold.com/t/defold-1-3-2-has-been-released/70822/12

**Comment by AGulev** [comment]
I confused something and the issue I was talking about in this forum post is related to sprites, not nodes https://forum.defold.com/t/defold-1-3-2-has-been-released/70822/12?u=agulev

So, probably there is no issue (everything works as expected) in this case, and you had an error message just because you changed the order of `gui.get_flipbook()`  and `gui.set_texture()`

>What I ALSO did, and this the cause of all my confusion, is move the gui.get_flipbook(node) AFTER gui.set_texture(), because the code is clearer that way - the animation id is not used by set_texture(), so why have the call before it? It’s likely the call was first because I had figured out it had to be, but I had no memory of that (and should have commented!).


I'm closing the issue but feel free to report if you find something suspicious
