### ISSUE TITLE
Speed up build size report generation

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6654]
**Task (REQUIRED):**
At the moment the process of creation build size report takes too long on a big project (up-to 30% of time for a big project).
I believe this can be nearly free. 
This should be investigated and optimized.

**Expected outcome (REQUIRED):**
Creation of the build time report takes up to a few seconds.

**Comment by AGulev** [comment]
https://github.com/defold/defold/issues/3814

https://github.com/defold/defold/issues/6045

**Comment by britzl** [comment]
The build size report is generated AFTER the build is completed. In a big project with a lot of files this is expensive since the work of generating the report is done on the already created game archive.

The data needed for the report should instead be collected during the build process when we write each resource to the archive. At that point in time we already have all of the information needed for the report.

A good starting point is probably to look at what goes in in the ArchiveBuilder:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameProjectBuilder.java#L214-L223

**Comment by britzl** [comment]
The build size report is generated AFTER the build is completed. In a big project with a lot of files this is expensive since the work of generating the report is done on the already created game archive.

The data needed for the report should instead be collected during the build process when we write each resource to the archive. At that point in time we already have all of the information needed for the report.

A good starting point is probably to look at what goes in in the ArchiveBuilder:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameProjectBuilder.java#L214-L223

**Comment by britzl** [comment]
The build size report is generated AFTER the build is completed. In a big project with a lot of files this is expensive since the work of generating the report is done on the already created game archive.

The data needed for the report should instead be collected during the build process when we write each resource to the archive. At that point in time we already have all of the information needed for the report.

A good starting point is probably to look at what goes in in the ArchiveBuilder:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameProjectBuilder.java#L214-L223

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/3316

**Comment by britzl** [comment]
It should be enough to parse the index since it contains compressed and uncompressed size per file.
