### ISSUE TITLE
Live update from non S3 storage

### ISSUE THREAD

**Issue by Grify** [defold/defold#6722]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I wish I could use my own already-existent servers to host live update content instead of dealing with Amazon and their S3 (especially the pricing beyond 1y)

**Describe the solution you'd like (REQUIRED):**
Custom live update sourcing online with support either for other services (DigitalOcean, etc) or custom HTTP endpoint (abc.xyz/liveupdate/file1) which the game will download the assets from once load is called.

**Describe alternatives you've considered (REQUIRED):**
A Defold proprietary cloud storage platform dashboard for linking storage to live updates and identifying issues or a Defold API for sending assets

**Comment by britzl** [comment]
This can be achieved with the current solution for live update. You can choose to export your content to a zip archive instead of to S3. Once you have the zip archive your can either upload the individual files or the entire archive to a hosting solution of your choice and download the files from there instead of from a public bucket on s3.

**Comment by Grify** [comment]
Thank you very much, I thought Zip was local-only.
