### ISSUE TITLE
Failed to connect to debugger on localhost:8172

### ISSUE THREAD

**Issue by Morpheus-6926** [defold/defold#6775]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-07-05T14:43:42.778079</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>42287cdfc623bf93319106a6e654a508ccf3beee</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"44be7091f102420489681b0d991640e9"'>44be7091f102420489681b0d991640e9</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 30.0.101.1338</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__44675.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:341)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
@Morpheus-6926 When does this happen? When you do Debug->Start/Attach (or press F5)? Does it work if you do Project->Build (or CMD/CTRL+B)?

**Comment by megalanthus** [comment]
### Expected behaviour
Application launch.
### Actual behaviour
A blank application window appears for a couple of seconds.
### Steps to reproduce
Empty project or any other when run via F5/ctrl-b/shift-ctrl-b

![image](https://user-images.githubusercontent.com/66716124/177981083-ea360f88-1c75-45ee-b88f-b3e468d79019.png)
![image](https://user-images.githubusercontent.com/66716124/177981312-0e214975-393b-489f-a5b8-d7663ce6d652.png)
<hr/>

<table>
<tr><td>Build time</td><td>2022-07-06T14:33:19.971468</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>05460a15a807b59ae35b8f2e2aabd3b1e745cbc7</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4d571f80138d4d688dfcc2e991a49276"'>4d571f80138d4d688dfcc2e991a49276</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 3GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>
