### ISSUE TITLE
Add 'lua' action to the editor scripts to call a lua function in the sequence.

### ISSUE THREAD

**Issue by astrochili** [defold/defold#6810]
I want to create folders and then run lua code to fill these folders with files.
Unfortunately, I haven't found a way to do these two steps consistently in the editor script.

Can't create a folder by the lua code because of the restrictions on using `os.execute`.
But can create folders with a separate shell action with calling `mkdir`.

But here are no folders yet at runtime of the lua code because the actions haven't run yet.
So I have to split my editor script into two commands which the user runs in the sequence by himself.

This looks very strange. Would be great to add lua code execution as a sequence action.

**Comment by astrochili** [comment]
I will make it asap but now you can look at this [script](https://github.com/astrochili/defold-trenchbroom/blob/master/trenchbroom/trenchbroom.editor_script).

**Comment by AGulev** [comment]
It's easy to fix, these functions [removed from the editor scripts intentionally](https://github.com/defold/defold/blob/0165677c0aabe3102206463e933668eed766e49f/editor/src/clj/editor/editor_extensions.clj#L784-L790)

**Comment by britzl** [comment]
@astrochili could you please explain the usecase and the problem you have?

**Comment by astrochili** [comment]
The usecase is creating folders and files during [importing from TrenchBroom](https://github.com/astrochili/defold-trenchbroom/#import-with-editor-script). I want to run lua code and create local folders in one command, but now it's not possible.

One way to do this is to make it possible to add a lua function calling to the actions array, in addition to `shell` and `set`. That way I can combine my shell command to create folders and lua command to create files in one command.

Removing restrictions to run [these functions](https://github.com/defold/defold/blob/0165677c0aabe3102206463e933668eed766e49f/editor/src/clj/editor/editor_extensions.clj#L784-L790) also can solve the problem, but more "lazy".

**Comment by vlaaad** [comment]
The original editor extension design separates reads (`editor.get`) and writes (actions) for several functions:
- mental model simplicity: this way, we can use a single editor state snapshot for the command function invocation (`active` or `run`). For the user, the results of `editor.get` are stable and don't change inside the function.
- performance: for `active` checks, we reuse the same editor state snapshot for every command from every extension.

If we want to add `os.execute` to `run` callbacks, there are some problems we need to solve. There might be an expectation that after `os.execute`, the editor performs a resource sync and updates the evaluation context so subsequent `editor.get` calls receive updated information.
We don't want `os.execute`, and especially resource sync, in `active` checks that are used to refresh context menus — this will destroy editor performance.

The way I see the problem is that you have a logic in lua that uses file io, but it has to run after a shell command, which currently cannot be invoked directly. This is a reasonable scenario.

I see 2 solutions to the problem:
- introduce `lua` action that is invoked with a fresh editor state snapshot. inside the associated function, `editor.get` calls are consistent, but the results might differ from calls in `run`. The action returns another array of commands to execute.
- deprecate the action system and instead introduce a side-effecting `transaction` editor API that applies multiple `set` actions in a single undoable step. Something like `editor.transact({node,key,val}, {node,key,val}, ...)`. Then, after the `editor.transact` or `os.execute` are invoked, we invalidate the editor snapshot, so subsequent calls to `editor.get` might return different results. We should also prevent calling these functions in `active` checks.

I prefer the second solution because the first one is semantically the same, but more verbose and alien, even though it's more data-driven, pure, etc. 

Open question: should we save the project before performing `os.execute`? I'd say yes. 
@matgis do you have some thoughts on the issue?

**Comment by matgis** [comment]
Yeah, there are a couple of ways we could deal with this scenario, but it is not as simple as just enabling the `os` functions.

@britzl maybe add this to the agenda for Thursday so we could discuss it a bit more before committing to a particular course of action here?

**Comment by vlaaad** [comment]
We decided to make several improvements to the editor scripts:
- #8425 
- #8426 
- #8427

**Comment by astrochili** [comment]
Good news, looks like a plan!

**Comment by vlaaad** [comment]
We now implemented and merged the first improvement (#8425).

**Comment by astrochili** [comment]
> We now implemented and merged the first improvement (#8425).

Great news, just checked it out in 1.6.4 beta - works as expected 👍

But I realised that this is only 1/2 of the unavailable functionality 🙈. Since the script syncs files, before creating a folder I also delete it - to get rid of unnecessary files.

Can I create a task similar to [#8425](https://github.com/defold/defold/issues/8425) about `editor.delete_directory(recursive: bool)` command?

**Comment by astrochili** [comment]
Created a [task #8472](https://github.com/defold/defold/issues/8472) and [PR #8472](https://github.com/defold/defold/pull/8473). Is it possible to include it in 1.6.4, complementing `create_directory`?

**Comment by vlaaad** [comment]
Even though we didn't add a `lua` action, we are closing this issue and considering it completed because we implemented a better solution, which is freely mixing "set" and "shell" actions in the Lua code using new editor script APIs: `editor.transact()` and `editor.execute()`. We also updated the [editor scripts](https://defold.com/manuals/editor-scripts/) manual to reflect the changes.
