### ISSUE TITLE
Frustum culling for tilemaps

### ISSUE THREAD

**Issue by britzl** [defold/defold#6938]
Add frustum culling for tilemaps (see https://github.com/defold/defold/pull/6445 as a starting point)

**Comment by Awasaky** [comment]
Hello. My upvote to this feature. This will help very much to create games like puzzle-platformers, because a lot of  off-drawing tiles still make game slow. Games like metroidvania and typical console platformers 8-16 bit era have an engine-based features to optimise offscreeen tiles. When gamedeveloper use tilemaps he looks to them as level-basement. But if tilemap of full level is big, then developer need to add additional code to show only tiles onscreen. As well now he can't use full level in development studio as is. This make development process of tile-based games harder than single screen based.
