### ISSUE TITLE
Cannot set a shortcut for the toggle comment with "Ctrl+'ù'" with or without the char '

### ISSUE THREAD

**Issue by DeRaNGeR** [defold/defold#7087]
**Describe the bug (REQUIRED)**
I have a problem to set a custom shortcut with my italian qwerty keyboard and set Ctrl+ù as toggle comment action

**To Reproduce (REQUIRED)**
1. Create custom keymap for windows as documentation says
2. edit the file and set the shortcut Ctrl+ù for the :toggle-comment action
3. restart defold
4. try

**Expected behavior (REQUIRED)**
when i hit Ctrl and ù toghether i suppose to comment the selected lines of code editor

**Defold version (REQUIRED):**
  - Version 1.3.7

**Platforms (REQUIRED):**
 - Platforms: any
 - OS: Windows 11
 - Device: PC

**Comment by beldenfox** [comment]
This is a limitation in JavaFX, it doesn't support shortcuts involving keys that generate accented characters largely because this is an unusual thing to do since they're not remotely portable across languages and locales.

I would not describe this as a bug in JavaFX but a limitation. There are changes to shortcut handling which might enable this behavior but only as a side effect if fixing other more obvious bugs. I believe openjdk/jfx#1126 will enable this but that PR is still awaiting approval.

**Comment by britzl** [comment]
Thanks @beldenfox ! I think we'll go ahead and close this issue for now.
