### ISSUE TITLE
In dmGameSystem::SetText() replace dmScript::CheckDDF() with direct message creation.

### ISSUE THREAD

**Issue by Lerg** [defold/defold#7089]
**Task (REQUIRED):**
In the code for the Label component (`gamesys/scripts/script_label.cpp`), the function which updates the label's text `SetText()` (Lua function `label.set_text("#label", "Text")`) uses Lua C API to create a temporary table just to call the `dmSript::CheckDDF()` function to initialize the message's data with the supplied text.

It should be possible to initialize the data structure with the correct data without using the `dmScript::CheckDDF()` function, which is intended for parsing messages that coming from the Lua runtime. Doing so will slightly improve the performance.

```c++
lua_newtable(L);
lua_pushlstring(L, text, len);
lua_setfield(L, -2, "text");

uint8_t data[dmMessage::DM_MESSAGE_MAX_DATA_SIZE];
uint32_t data_size = dmScript::CheckDDF(L, dmGameSystemDDF::SetText::m_DDFDescriptor, (char*)data, sizeof(data), -1);
```

https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/scripts/script_label.cpp#L207

**Expected outcome (REQUIRED):**
The SetText() function no longer uses dmScript()::CheckDDF() function for creating a message.

**Comment by britzl** [comment]
We have no immediate plans to change this (or other places where the same kind of pattern can be seen). If someone is interested in making a concerted effort of optimising this in the engine we're very open to discuss any incoming PR. One approach could be to start with a PR for this case to be better understand what it might look like.

**Comment by Lerg** [comment]
@britzl please explain the principals of constructing a DDF message. In other places the dmMessage::PostDDF() is used
```
dmGameObjectDDF::Enable message;
dmMessage::PostDDF(...)
```
How is the SetText message different? I understand it has something to do with allocating space for the text.
But what essential pieces are missing for it to work? What is the layout of dmGameSystemDDF::SetText?

There are no generated *_ddf.h files in the dmsdk. Could they be added? Or at least provide the one for SetText?

**Comment by JCash** [comment]
I don't see it as a huge problem sharing the _ddf.h file (since they're generated), although we do changes there from time to time.
However, it's not a priority for us right now.

The struct, is basically just a struct, and ofc since it's dynamic, the payload needs to be stored afterwads:
`buffer = Struct+Payload´

The way it's done is that the `const char*` is actually storing an offset into the payload part of the message.
And then, when receiving, the receiver can "resolve" the pointers, and get a workable `const char*`.

See script_http.cpp/Http_Request() for reference.

**Comment by Lerg** [comment]
@JCash thanks, that was helpful, I got it working.
