### ISSUE TITLE
Sprite Trim produces overlapping polygon shape

### ISSUE THREAD

**Issue by Lerg** [defold/defold#7389]
### Expected behaviour
When sprite trimming is enabled I would assume a convex polygon shape should be generated for an image.

### Actual behaviour
The polygon shape is not convex and has overlaps.

### Steps to reproduce
I've prepared a test project https://github.com/Lerg/defold-sprite-trim-bug
You can see the issue on the video https://github.com/Lerg/defold-sprite-trim-bug/blob/main/preview.mp4

<hr/>

<table>
<tr><td>Build time</td><td>2023-02-16T09:14:16.933310</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5f92b6941a3d552a64bf69287c51e618d6d45534</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.1</td></tr>
<table>

**Comment by JCash** [comment]
<img width="268" alt="Screenshot 2023-02-17 at 08 54 32" src="https://user-images.githubusercontent.com/1349334/219584824-6a16d6c1-6ef9-456b-8aa9-cb86d4ed3408.png">

I have to say it's a bit surprising since I would also expect the actual sprite to be messed up, but it isn't.
Which leads me to believe that these are extra polygons somehow, and they're have transparent pixels.

I'll look into it.

**Comment by JCash** [comment]
@Lerg May I use `Erica_run_23.png` as a unit test image? I can e.g. make it black&white to make it unusable by others, and rename it `test_image_7389.png`.

**Comment by Lerg** [comment]
@JCash sure, all are free as test subjects, no need for special edits.
