### ISSUE TITLE
.defignore needs to work in subfolders

### ISSUE THREAD

**Issue by subsoap** [defold/defold#7560]
.defignore currently only works if it's in the root of the project, but it needs to work in subfolders too (like .gitignore does) so that libraries can exclude some files as well.

**Comment by britzl** [comment]
Can you give an example of the kind of file a library would want to exclude? And if a library wants to exclude a file, then why put it into a shared library folder in the first place?

**Comment by subsoap** [comment]
https://github.com/aglitchman/defold-playable-ads

An example, it would be nice if a .defignore could be added to the [playable_ad](https://github.com/aglitchman/defold-playable-ads/tree/master/playable_ad) folder as when you add it to your project and run it once it adds the node_modules file with tons of files. People who want to use this would need to add the folder to the root of the project's .defignore but a lot of people don't know about .defignore and so a lot of time will be wasted loading projects like this for them. There will probably be similar examples of this in the future as people build helper tools that live in the project directory and use tools like node.

**Comment by subsoap** [comment]
Here's another case where it's an issue that's annoying, you have the Defold editor open and add a library like playable_ad, then run node install to set it up, go back to Defold and it appears to hang because it has to process those thousands of files created in the node_modules folder.

**Comment by JCash** [comment]
> when you add it to your project and run it once it adds the node_modules file with tons of files

I think it's not good that another tool adds build/temp data directly into the project folder, other than the actual `./build` folder.

Where do these files end up you say? They can't be placed under `./playable_ad`, since that's a virtual folder (the .zip file).

**Comment by subsoap** [comment]
It's manually placed not as a library listed in the game.project file

https://github.com/aglitchman/defold-playable-ads

You can test it to see what happens when you add it to a project / run npm install then go back to the editor

Currently I am adding its node_modules folder to the root Defold .defignore but I am still predicting this will be a reoccurring annoyance for people in the future to not be able to have .defignore files in subfolders of a project/in a library so some of its files are entirely ignored by editor.

**Comment by vlaaad** [comment]
This is a feature request; the problem this feature request is supposed to solve is that an extension puts intermediate build results into the project files instead of a `./build` folder. Another solution to this problem would be contributing a change to the playable-ads repo so it puts intermediate build results in a `./build/plugins/playable-ads` folder instead. I think this should be possible because it seems it's possible to [configure the `node_modules` folder location](https://stackoverflow.com/questions/14742553/how-to-set-custom-location-for-local-installation-of-npm-package).

Side note: another contribution to playable-ads library could be changing the file paths in the library so it can be added as a regular dependency. My understanding is the current installation approach (copy folder) exists because the tools need files on disk, not entries in a zip archive. Both Defold editor and Bob now can extract some plugin files from the dependency — if a folder with `ext.manifest` file has `plugins/bin` subfolder, it will be [extracted as described here](https://defold.com/manuals/editor-scripts/#editor-scripts-in-libraries).

**Comment by britzl** [comment]
I think we should go with the recommended solutions by @vlaaad and not focus any additional effort on how .defignore files are handled.
