### ISSUE TITLE
collectionfactory.set_prototype fails to load new prototype

### ISSUE THREAD

**Issue by john-cheesman** [defold/defold#7640]
**Describe the bug (REQUIRED)**
When calling `collectionfactory.set_prototype` the following error is logged:
```
ERROR:GAMESYS: failed to load collection prototype [/main/level2.collectionc]
ERROR:SCRIPT: main/level_loader.script:3: Failed to load collection factory prototype /main/level2.collectionc
stack traceback:
  [C]:-1: in function set_prototype
  main/level_loader.script:3: in function <main/level_loader.script:1>
```

**To Reproduce (REQUIRED)**
Create a new project with a main.collection, level1.collection and level2.collection. Add a game object with a collection factory called 'level_factory' to main.collection. Set the prototype to level1.collection and check the 'dynamic prototype' field. Add a script to the game object with the following init function:
```
function init(self)
    collectionfactory.unload('#level_factory')
    collectionfactory.set_prototype('#level_factory', '/main/level2.collectionc')
    collectionfactory.create('#level_factory')
end
```
Build and run the project.

**Expected behavior (REQUIRED)**
The collection factory should load the new prototype without error.

**Defold version (REQUIRED):**
1.4.5

**Platforms (REQUIRED):**
Linux

**Minimal repro case project (OPTIONAL):**
https://github.com/john-cheesman/collection-factory-bug

**Comment by britzl** [comment]
This is actually not a bug. The Defold resource archive will only include content that is used or referenced by your game. When we build your game we start at the bootstrap collection and build a graph of referenced resources and only include these resources in the build:

* a game object used in a collection
* a collection used in another collection
* a game object referenced by a factory
* a collection referenced by a collection factory
* a collection referenced by a collection proxy
* a resource referenced from a script property (eg `go.property("foo", resource.atlas("my.atlas"))`)

So in order to use `set_prototype` [example](https://defold.com/ref/stable/collectionfactory/#collectionfactory.set_prototype:[url]-[prototype]) the new prototype you set must be included in the resource archive. The other option is of the new prototype was included in a loaded LiveUpdate resource bundle.

So what you need to do in your case is to make sure there is a reference to `level2.collection` somewhere in your project. Three ways you can do this:

1. Reference `level2.collection` from a collection factory
2. Reference `level2.collection` from a collection proxy
3. Load `level2.collection` using LiveUpdate

<img width="380" alt="Screenshot 2023-05-11 at 09 31 59" src="https://github.com/defold/defold/assets/1300688/8fead59f-fd6c-4ac6-afaa-728f602447f3">

**Comment by john-cheesman** [comment]
Great, thanks for the explanation :+1:
