### ISSUE TITLE
Bob builds a project when its title is empty

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#7677]
**Describe the bug (REQUIRED)**
If I set a project title setting in `game.project` to an empty string and then try to bundle an Android app, the build succeeds, but no APK is created.

**To Reproduce (REQUIRED)**
1. Create a new project from the Empty template
2. Open `game.project` in the editor
3. Set `Title` to setting to empty string
4. Bundle for Android platform

**Expected behavior (REQUIRED)**
The build fails

**Defold version (REQUIRED):**
  - latest

**Comment by AGulev** [comment]
Are we sure about expected behavior?

**Comment by britzl** [comment]
> Are we sure about expected behavior?

No, but I'm not sure I would expect a bundle to be created if the project has no title. Or should we fallback to some default name (unnamed.apk)?

**Comment by AGulev** [comment]
@britzl we have fallback

>projectProperties.getStringValue("project", "title", "Unnamed");

 but now we don't use Default ("Unnamed") value for properties if the property is an empty string (we use default value only in case if the property doesn't exist). So, as result bundler uses empty string everywhere and breaks in some places.

We have two ways to go:
1. Simple and safe way is to check in the beginning if title is an empty string and throw exception with a message that explains the reason.
2. Change property reader and make an empty string is an invalid value and if so use Default value. More likely it will need extra changes in bundlers and also may break some behavior in the other places (if somebody want to use an empty string as property by design, I don't remember such cases, but who knows)

**Comment by britzl** [comment]
> * Simple and safe way is to check in the beginning if title is an empty string and throw exception with a message that explains the reason.

I think this is acceptable. Or is there a use-case to set the title to an empty string?

**Comment by AGulev** [comment]
> > * Simple and safe way is to check in the beginning if title is an empty string and throw exception with a message that explains the reason.
> 
> I think this is acceptable. Or is there a use-case to set the title to an empty string?

I don't think so.
btw. I think project build fine with empty name, but it is invisible because it is `.app` - so it is hidden folder (at least on mac).
