### ISSUE TITLE
gui.play_flipbook() not firing "completion" function

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#7758]
**Describe the bug (REQUIRED)**
changing a gui node image with "gui.play_flipbook()" used to execute a callback function, but since 1.4.6 and on, it has stopped working.

**To Reproduce (REQUIRED)**
Run attached program in Defold editor.

**Expected behavior (REQUIRED)**
Callback function should execute after the gui image change

**Defold version (REQUIRED):**
Current version is 1.4.7

**Platforms (REQUIRED):**
Windows 10

**Minimal repro case project (OPTIONAL):**
[GUI_shader.zip](https://github.com/defold/defold/files/11842179/GUI_shader.zip)

**Comment by britzl** [comment]
I believe this is caused by a recent change we did to conserve resources in large gui scenes with many textures.

https://github.com/defold/defold/pull/6458

We previously created implicit one-frame animations for single images in an atlas. This caused problems in large guis with many or large atlases. The of number animation references could quickly hit the cap in such a scenario. If you really need a single image to be treated as an animation then please create an animation group and assign the image.

What we probably can look into is to immediately call the callback function even in the case of an implicit one frame animation.

**Comment by jcbk101** [comment]
Thank you very much. I was using animations, but changing the image using CURSOR. Will adjust this.


________________________________

**Comment by britzl** [comment]
> but since 1.4.6 and on

I don't think this is correct. I get the same result with no callback in 1.4.5 for instance. I believe this issue has been here since 1.3.1 when the behaviour was changed.

**Comment by jcbk101** [comment]
To be honest, the animation that uses that feature has not be tested since it has been settled. I am not sure but I think the last time I tried it was last year.


________________________________

**Comment by britzl** [comment]
> I believe this issue has been here since 1.3.1 when the behaviour was changed.

Sorry, I was wrong. After looking at the code changes in 1.3.1 and then testing newer versions this breaking change was introduced in Defold 1.4.4.

**Comment by jcbk101** [comment]
Okay. So I was close. Will there be a fix/workaround maybe?


________________________________

**Comment by Jhonnyg** [comment]
> Okay. So I was close. Will there be a fix/workaround maybe?
> […](#)

Yes we’ll fix it 👍
