### ISSUE TITLE
Editor updater should handle if downloaded update is empty or otherwise corrupt

### ISSUE THREAD

**Issue by sergionikol** [defold/defold#7933]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-07-17T16:06:12.143105</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a26e44ba65cdefe580af2e199833478fc49472b</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"74761c5fde814776b40170f7dd1bf280"'>74761c5fde814776b40170f7dd1bf280</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.2.1</td></tr>
<table>

**Comment by AGulev** [comment]
![telegram-cloud-photo-size-2-5438440530141892056-y](https://github.com/defold/defold/assets/2209596/e649449d-1b68-4d82-baf7-9641b0bbdaff)

**Comment by AGulev** [comment]
It's corrupted archive. Removing and fetching again - helps.
@matgis @vlaaad maybe we can try to remove archive and download it again if we catch such an error (at least once)? or show more informative message (what extension it is and what user should do?)

**Comment by AGulev** [comment]
copied from  https://github.com/defold/defold/issues/5327 : 
Task (REQUIRED):
The updater doesn't handle if the downloaded zip update archive is empty or otherwise corrupt. It repeated tries to unpack the same file. The editor should remove a downloaded update if it fails to apply it.

Expected outcome (REQUIRED):
The editor should handle corrupt update archives and re-download and try updating again.
