### ISSUE TITLE
Change to tar for Linux release?

### ISSUE THREAD

**Issue by rama0x9** [defold/defold#8052]
Would it be possible to package future Linux releases using tarball instead of zip as is currently the case? Tar is built into pretty much every *nix system, and its respect and support is much better. Would greatly appreciate it.

**Comment by britzl** [comment]
Yes, that is totally possible.

These are the lines of code responsible for packaging the editor:

https://github.com/defold/defold/blob/dev/editor/scripts/bundle.py#L460-L466

We can add a platform check and tar instead of zip when the platform is Linux. We also need to take care of the side effects of this change:

- Make sure that upload scripts still work
   -  upload to s3
   - [upload to GitHub](https://github.com/defold/defold/blob/dev/build_tools/release_to_github.py#L148)
   - [upload to Steam](https://github.com/defold/defold/blob/dev/build_tools/release_to_steam.py#L100) (will it work with .tar files on Steam?)
- Make sure download links work on the website
   - https://github.com/defold/defold.github.io/blob/master/download.html#L39

**Comment by vlaaad** [comment]
Note: If we want to introduce this change, we will also need to fix the editor [updater logic](https://github.com/defold/defold/blob/9086e51f7547c24fb4a135ad079934ae1af69829/editor/src/clj/editor/updater.clj#L154) that relies on updates existing as zip files to update the editor.

But even before we start changing the code, I think we should make sure we actually want to do that. When we consider changes to Defold, we start with the problem we are trying to solve. You didn't specify the problem with zip files, but I assume we can infer that the problem here can be defined like this: "Installation experience on Linux could be more convenient". 

Then, when we have a problem, we can consider solutions. Here are a couple of alternative solutions to this problem:
- distribute the Linux version as a `.tar.gz` file
- distribute the Linux version as a `.dpkg` file

Then, we can consider the trade-offs of these alternative solutions. For example, when distributing the Linux version as a `.dpkg` file, we lock out non-Debian distros — they are not supported anyway, but Defold editor might actually work there anyway. We also need to create a zip file for the editor updates. When distributing as `.tar.gz`, we have 2 options: do it in addition to `.zip`, so that the updater works as is (similarly to how macOS has both `.dmg` and `.zip`), or change the updater logic so it can unpack both `.tar.gz` and `.zip`.

I'm also not convinced that `.tar.gz` provides a better installation experience than `.zip`. When using GUI, both `.zip` and `.tar.gz` files are extracted in exactly the same manner: `Right Click` -> `Extract Here`, so the change does not improve the installation experience. When using a terminal, I would argue that `unzip file.zip` is a much better user experience than `tar xzf file.tar.gz` — a simple command expecting a single file as an argument versus a complex swiss-knife command that requires remembering a mnemonic "e**X**tract **Z**e **F**ile" to actually do the extraction.

I think the Defold editor could be distributed in a more convenient way. Ideally, I want it to be as simple as `apt install defold` on Linux, `brew install defold` on macOS, etc. 

Maybe there are simpler improvements, like adding `.tar.gz` as a download option in addition to `.zip`, while keeping the `.zip` as a default because IMO it's more convenient for the average user. Let's discuss this first before changing the code!

**Comment by colorizer** [comment]
I second the idea to add `tar.gz` as an option for Linux users instead of a replacement.

**Comment by vlaaad** [comment]
Awesome, let's do this! This would also be easier to integrate since we don't need to remove any existing handling of zip files.

**Comment by vlaaad** [comment]
We now provide tar.gz as a download options for Linux: https://defold.com/download/
