### ISSUE TITLE
Implementing HAVOK as the 3D physics engine

### ISSUE THREAD

**Issue by ProgrammingLife** [defold/defold#8106]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Yes, the actual physics engine is not so perfect it has many strange behaviour moments like going through the collisions and others.

**Describe the solution you'd like (REQUIRED):**
Implementing HAVOK engine as the 3D physics engine. Since this is the de facto standard in the gaming industry.

**Describe alternatives you've considered (REQUIRED):**
HAVOK - the fastest physics engine, with the best performance, no alternatives here.
It works great in Babylon.js.

**Additional context (OPTIONAL):**
I hope this will be implemented somehow ^_^

**Comment by aglitchman** [comment]
> HAVOK - the fastest physics engine

Could you please provide references to benchmarks?

**Comment by britzl** [comment]
Isn't Havok proprietary tech with some licensing cost? We are planning to make the physics system in Defold extensible so that Box2D and Bullet 3D become internal extensions which can be replaced by other physics engine extensions while retaining editor support. Once we have that in place it is possible for someone to create a Havok physics extension for Defold.

Closing this feature request.
