### ISSUE TITLE
Bundling and launching for Android automatically enables the accelerometer rotation

### ISSUE THREAD

**Issue by ultimanidev** [defold/defold#8223]
**Describe the bug (REQUIRED)**
When bundling and launching an app for Android from the editor, the accelerometer rotation on the target device gets enabled. This issue is related to [monkey](https://stackoverflow.com/questions/56684778).

**To Reproduce (REQUIRED)**
1. Go to Project -> Bundle -> Android Application
2. Check "Launch installed app"
3. Click on "Create Bundle"

**Expected behavior (REQUIRED)**
The app launches on the device, but you can see that the auto-rotate is enabled on its own.

**Defold version (REQUIRED):**
  - Version: 1.6.1

**Platforms (REQUIRED):**
 - Platforms: Android

**Workaround (OPTIONAL):**
It is possible to obtain the state of the accelerometer rotation before launching and restore it afterwards. As an alternative to the monkey tool, launching through `adb shell am` with the activity name and package name is better to avoid the issue altogether.

**Comment by vlaaad** [comment]
Hey, many thanks for describing the issue! I personally think that it would be better to use `am -start` instead of `monkey`, since it does not require any workarounds. As I understand, the implementation would need to access the activity class name, which should be [com.dynamo.android.DefoldActivity](https://github.com/defold/defold/blob/fccc521aa2107d86ceec59340b95ad56dc00faad/engine/engine/content/builtins/manifests/android/AndroidManifest.xml#L24).

**Comment by vlaaad** [comment]
Would you be willing to change your PR so it uses `am start` instead of `monkey`? Also, it should target `editor-dev` branch instead of `dev`.

**Comment by vlaaad** [comment]
Thanks a lot for doing it (twice!). I'll review it tomorrow when I will be able to test it.
