### ISSUE TITLE
Video Playback for Defold

### ISSUE THREAD

**Issue by ahmutkadim** [defold/defold#8440]
_Is it a private platform specific feature? (i.e. would it break your NDA?)<br>
Then please add your feature request in the corresponding extension repository!_

**Is your feature request related to a problem? Please describe (REQUIRED):**

Defold cannot play a video file, in some games, some cut-scenes are played as videos and Defold not having a native feature of playing videos hinders its capability of developing games.

**Describe the solution you'd like (REQUIRED):**

Implementing a video-playback framework would be reasonable request since  Defold uses C/C++. A simple api of playing popular file formats like mp4, mov would be enough with pausing, getting and setting the progress.

**Describe alternatives you've considered (REQUIRED):**

I believe it is far fetched but might there be a way of using atlas files to import videos as animations and take the sound track as a separate sound component.

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
> Implementing a video-playback framework would be reasonable request since Defold uses C/C++. A simple api of playing popular file formats like mp4, mov would be enough with pausing, getting and setting the progress.

We will not add video player support in the engine core. A video player should be implemented as a native extension. There is already an example extension based on libvpx:

https://github.com/defold/extension-videoplayer

Also, if you are specifically targeting iOS and Android there's this native player:

https://github.com/defold/extension-videoplayer-native

Two additional solutions would be 1) use the [webview extension](https://github.com/defold/extension-webview) or 2) if this is an html5 game you could use a `<video\>` tag in your html5 template and play/pause using `html5.run()`

**Comment by ahmutkadim** [comment]
In the first link you provided it says:

"NOTE: This is an example extension, with no sound support. To use a native videoplayer (Android/iOS), we recommend [extension-videoplayer-native](https://github.com/defold/extension-videoplayer-native) instead."

The other example you provide is specific to mobile devices and the other solution you offer about web can only cover an html5 build. This leaves desktop builds open and someone who attempts to implement video playback for a desktop application would not be able to. Due to not core implementation of the engine, these extensions try their best with creative solutions like using different apis for different platforms. However I can say that even with the addition of all these extensions, the feature is not supported cross-platform even I am not mentioning console.

**Comment by britzl** [comment]
> In the first link you provided it says:
> 
> "NOTE: This is an example extension, with no sound support. To use a native videoplayer (Android/iOS), we recommend [extension-videoplayer-native](https://github.com/defold/extension-videoplayer-native) instead."

Correct. And in my answer I write _"There is already an example extension"_. It is an example that someone could expand upon to add sound, or use as the foundation for their own video player extension.

> The other example you provide is specific to mobile devices

Correct. You did not mention which platforms you are targeting. If it happens to be mobile then extension-videplayer-native will work very well for you.

> Due to not core implementation of the engine, these extensions try their best with creative solutions like using different apis for different platforms

Well, playback of video will not end up in the Defold engine core. It is not in line with the design philosophy of Defold. Video playback should be implemented as an extension.

The example extension, https://github.com/defold/extension-videoplayer, is cross platform, but does not support audio. I suggest that you help out by researching and recommending a cross platform video and audio decoder and share your findings here or in https://github.com/defold/extension-videoplayer. In the research I suggest to pay special attention to the size of the decoder and to some extent also decoding performance.

We could then bring your findings to the Defold community on Discord and on the forum and see if someone (or you) would be willing to implement it.

**Comment by ahmutkadim** [comment]
> It is not in line with the design philosophy of Defold

Could you please elaborate on what this design philosophy is so I may not mention some future requests I would come up in the future.

**Comment by britzl** [comment]
> > It is not in line with the design philosophy of Defold
> 
> Could you please elaborate on what this design philosophy is so I may not mention some future requests I would come up in the future.

Sure. Although there's nothing wrong in posting feature requests for new extensions to the engine core, so even if a feature doesn't have a place in the engine core it may be well suited for an extension.

First of all I'd like to point you to this page: https://defold.com/why/. The page outlines some of the arguments for using Defold and what makes it different in some regards when compared to other engines. In this case I'd say that "No breaking changes", "Small and performant" and "Low level building blocks" describe why a video player should be an extension and not a core feature.

### No breaking changes
In order to have an engine where breaking changes are introduced very rarely we need a small and well designed public facing API. If we add all kinds of SDK integrations, library dependencies and open source dependencies it is more likely that something changes somewhere at some point which forces us to introduce a breaking change. It could be an OS update which deprecates APIs or security issues in an SDK or something else outside of our control. This can often be solved "inside" the engine without interfering with the public APIs, but we can't always guarantee it. And when that happens it will result in a breaking change. And the more integrations we have in the engine core the more often breaking changes will occur. If we instead have these integrations, services and features in extensions we can keep a small public API in the engine core and more freely update extensions as dependencies and requirements change over time without disrupting anything in the engine core.

### Small and performant
We want to keep the engine core small and performant at all times. Every time we add something to the engine core we bloat the engine. We can design new large features in such a way that we can replace the implementation with a null implementation when a developer doesn't need the feature, but it requires more work than if the feature was an extension.

### Low level building blocks
The philosophy of providing low level building blocks through the Lua API also translates to the C++ API for extensions. We provide the low level building blocks and hooks so that developers can create the high level functionality they need as reusable and shareable library projects.
