### ISSUE TITLE
Confusing LINEAR min filter in game.project

### ISSUE THREAD

**Issue by vbif1** [defold/defold#8443]
We bumped to this situation several times in our telegramm community. People tend to think that LINEAR mag filter is LINEAR or LINEAR_MIPMAP_LINEAR. But in reallity it's LINEAR_MIPMAP_NEAREST. And because of mipmap button hided deep in textures profiles people complains about blurry pictures. This behaviour also not mentioned in the [docs](https://defold.com/manuals/project-settings/#default-texture-min-filter) and [docs](https://defold.com/manuals/texture-filtering/)

Maybe we should have all 6 filters options in this combobox?
Or maybe it's better to disable mimmap by default https://github.com/defold/defold/issues/6191

place in code
https://github.com/defold/defold/blob/eacd75e6216e23cceeb41e591f8953800e381dd1/engine/engine/src/engine.cpp#L396

**Comment by Scmorrka** [comment]
"Make more clear description and control for "Default Texture Min/Mag Filter" in game.project"

Currently, "Default Texture Min/Mag Filter" shows choice "linear/nearest". However, actually this option works only if "mipmap" is on in texture profile and changes filtering between LINEAR_MIPMAP_LINEAR and LINEAR_MIPMAP_NEAREST.

It is confusing, because nor title, no doc (https://defold.com/manuals/texture-filtering/) never mention mipmap.

Suggestion - change description in game.project to 
"Default Texture Min/Mag Filter for mipmap" and choices from linear/nearest to LINEAR_MIPMAP_LINEAR / LINEAR_MIPMAP_NEAREST

**Comment by AGulev** [comment]
## How it works
1. We specify Defaults in `game.project` where we have two options `linear` and  `nearest`
![Pasted image 20240123133825](https://github.com/defold/defold/assets/2209596/1069175d-4779-44ff-b3c0-22de0d386da8)

2. For `Mag filter` it is how it is `TEXTURE_FILTER_LINEAR` and `TEXTURE_FILTER_NEAREST` (Mag has only these two options) 
<img width="154" alt="Pasted image 20240124100457" src="https://github.com/defold/defold/assets/2209596/66b285ed-bf5b-4331-80b5-711813646e17">

3. for `Min Filter` it is `TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST` and `TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST`
<img width="204" alt="Pasted image 20240124100512" src="https://github.com/defold/defold/assets/2209596/8fab2e20-da4f-4bee-90e9-9966f6fdf991">

4. These defaults are used by the materials without texture sampler or (starting Defold 1.6.4) by the fields in texture samplers where "Default" filtering specified

5. Since using of a filter with mipmap without having an actual mipmap in a texture may break a sampler, we use fallback. This fallback works like: if `Min` filter uses mipmap but the texture doesn't have one, then `Min Filter` = `Mag Filter`: https://github.com/defold/defold/blob/d442e43596000a2fd250571e0b0276b613ed79a6/engine/graphics/src/opengl/graphics_opengl.cpp#L2916-L2919

## What to do

The next step is to decide how to explain it in the best form.

>  the [docs](https://defold.com/manuals/project-settings/#default-texture-min-filter) and [docs](https://defold.com/manuals/texture-filtering/)
Of course, we should improve our manuals.

But also, we need to decide if we need a new checkbox which turn mipmaps off for texture filtering OR an extra option for `Default Texture Min Filter` which will make it possible to pick a non-mipmap version of texture filtering.

**Comment by AGulev** [comment]
> Fallback looks strange maybe you should clamp all variants of linear with mipmap to just linear (and nearest mipmap to nearest). 

Fallback is important, otherwise it will be crash. 
We can't just change defaults and break all the existent projects. We don't do things like that.

>I also heard that you want to introduce default option in filtering that would use project config. And that settings must somehow works with atlas with different mipmap setting. How that would work?

No, nothing like this. It will be `Default` option like one of the filtering options here (it's explained in my post in p.4):
![image](https://github.com/defold/defold/assets/2209596/3233cfd8-8484-4765-ba8f-31e93ad0ce5b)
![image](https://github.com/defold/defold/assets/2209596/5dede137-a3c5-43a7-a3b8-8342baec9f3e)

>Or maybe you should make 3 options for filtring (mag, min w mipmap, min without mipmap) with only correct variants of filtering.

Yes, this is one of the options and this is what I meant here:
>an extra option for Default Texture Min Filter which will make it possible to pick a non-mipmap version of texture filtering.

We didn't decide yet.
