### ISSUE TITLE
Wavefront OBJ Support

### ISSUE THREAD

**Issue by hawl1** [defold/defold#8568]
**Is your feature request related to a problem? Please describe (REQUIRED):**
No it is not related to a problem.

**Describe the solution you'd like (REQUIRED):**
Make a Wavefront OBJ loader.

**Describe alternatives you've considered (REQUIRED):**
I didn't really considered alternatives since its the only solution.

**Comment by britzl** [comment]
We made the decision a while back to move from Collada to glTF as the main format for 3D models. We have no plans to add support for more formats BUT we may in the future add plugin support so that developers can write their own importers. In the meantime I suggest that you convert your obj files to glTF using Blender or similar software.
