### ISSUE TITLE
Occasional object teleportation (game speed up) on Macbook Pro M1 Max

### ISSUE THREAD

**Issue by kirilllysenko** [defold/defold#8948]
Bug description:

When playing some Defold sample projects objects are being teleported. It looks like occasionally 1 in-game second passes during 1 frame. Better to see attached videos to understand

1. Create new project in Defold from one of the projects below
1.1. From template "Platformer game"
1.2. From sample "Lightning VFX"
1.3. From sample "Pixel line platformer"
2. Run game using Project -> Build
3. Play game for some time and see bug

Expected behavior:
Playing game without occasional object teleportation (game speed-up)

Defold version:
  - Version 1.8.0
  - Channel: editor-alpha
  - Build time: 2024-05-1515:14:00.109381
  - Defold CPU arch: Apple Silicon

Platforms:
 - Platforms: MacOS
 - OS: MacOS Sonoma 14.4.1
 - Device: Macbook Pro M1 Max

Minimal repro case project:
https://github.com/defold/template-platformer/archive/main.zip
https://github.com/defold/sample-pixel-line-platformer/archive/refs/heads/main.zip
https://github.com/FlexYourBrain/sample_LightningVFX/archive/master.zip

Videos of bug:
https://github.com/defold/defold/assets/47689344/0d74ef64-6c11-4cb0-9dc9-456ac9b3d01b
https://github.com/defold/defold/assets/47689344/9cbb5b44-e217-418d-ac5d-4aa90209e3eb
https://github.com/defold/defold/assets/47689344/64bce953-d2fa-4b3b-904d-9341292af801

Additional Info:
On some sample projects there is no such problem

**Comment by gianmichelemariani** [comment]
I'm experiencing the same issue. My specs are slightly different:

- Platform: MacOS
- OS: MacOS Ventura 13.6.6
- Device: Macbook Pro 16 M1Pro
- This happens both with battery and connected to power brick.

**Comment by Jhonnyg** [comment]
Setting the "update frequency" to zero seems to remove the warping in both projects, we'll need to do some more investigation as to why the frame delta occasionally spikes.

**Comment by coelhucas** [comment]
Tested on my Apple M1 Pro, it happens as well. Was able to also test on my partner's MBP Intel and the issue didn't happen, seems to be ARM specific.

macOS Sonoma 14.4

Also made a video, although probably not much needed:
https://www.youtube.com/watch?v=LbG1_trzaxI

I'm pretty much a newcomer to Defold but from a shallow look on the code everything [here](https://github.com/defold/defold/blob/82777cfcb5e00ee06d471036ab81bde1a4e3d331/engine/engine/src/engine.cpp#L1837) seems fine, is it possible to actually? be an issue on GLFW Such as https://github.com/glfw/glfw/issues/2268

**Comment by selimanac** [comment]
> Setting the "update frequency" to zero seems to remove the warping in both projects, we'll need to do some more investigation as to why the frame delta occasionally spikes.

I have opposite result. If I set it to 0 I have spikes. If I set it to anything, I got less spikes(almost none)


### Expected behaviour

### Actual behaviour

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-10-16T15:01:14.208685</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>770aa9209edba2be234d7b9edee7502bf02a40f2</td></tr>
<tr><td>Defold engine sha</td><td>770aa9209edba2be234d7b9edee7502bf02a40f2</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.7</td></tr>
<table>
