### ISSUE TITLE
http.request report_progress updates one time per second. I need more updates per second

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8966]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I am loading liveupdate in http.request.I need to show progress bar for player.

Callback for progress called one time per second. You can see step on progress bar, this looks not good

https://github.com/defold/defold/assets/2655263/d01106e4-7eb0-4d0c-825c-293175e577c7

DEBUG:SCRIPT: [INFO 15:45:35] none: libs_project/liveupdate.lua:103: liveupdate loaded	0.1166659307531
DEBUG:SCRIPT: [INFO 15:45:36] none: libs_project/liveupdate.lua:103: liveupdate loaded	0.15555457433747
DEBUG:SCRIPT: [INFO 15:45:37] none: libs_project/liveupdate.lua:103: liveupdate loaded	0.19444321792183
DEBUG:SCRIPT: [INFO 15:45:38] none: libs_project/liveupdate.lua:103: liveupdate loaded	0.2333318615062

**Describe the solution you'd like (REQUIRED):**
1)Add parameter to request. If i need i will change delay
```lua 
{ report_progress = true, report_progress_delay = 0.1 }
```
2)Or send progress every frame
**Describe alternatives you've considered (REQUIRED):**
Now i use lerp for progress, so it looks less steps

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
We are not throttling progress updates. We send it make to the caller as soon as we receive progress updates:

https://github.com/defold/defold/blob/dev/engine/script/lib/js/library_script.js#L29-L33

[This SO comment](https://stackoverflow.com/a/5543745/1266551) seem to indicate that it may happen every 50ms, but I don't see anything about it in the spec. I guess it happens when the browser thinks it is appropriate. If you can find an actual way to configure it please let us know!

**Comment by britzl** [comment]
> not sure what is happening(

I blame the browser! Have you tried in different browsers to see if there is a difference?
