### ISSUE TITLE
Hide html5 preloader only when bootstrap collection loading is done

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9018]
Or maybe after `Module.callMain()`

**Comment by ekharkunov** [comment]
Tried to test in following way:
1. Create lots of atlases different size (2kx4k, 4kx4k)
2. Reference it from bootstrap collection
3. Apply texture profiles to produce compressed textures
4. Build and run project
Observe following behavior: loader banner and progress bar shows and updated. In some moment of time progress bar stop updated but still visible. Than progress bar and loader banner hid and game starts.

Probably that issue was fixed when dmloader.js was reworked in https://github.com/defold/defold/pull/8682
