### ISSUE TITLE
How to use LuaRocks modules on Defold

### ISSUE THREAD

**Issue by Sasanidas** [defold/defold#9114]
So, I was trying to found a way to easily load external libraries into Defold, I realize that it doesn't seem an easy task (even for simple libraries), as the require functions fails to find modules that have multiple files (even in the same folder). 

I'm guessing this is because the way that Defold look for modules/files. 

Is there any easy way to work with external libraries?

Regards

**Comment by britzl** [comment]
It is possible to add your own package loader to look for Lua modules in other locations (https://www.lua.org/manual/5.1/manual.html#pdf-package.loaders). BUT it will not work in the cases where you bundle your game into an archive and upload it to for instance Steam. If you wish to use LuaRocks modules in a released game you need to copy the modules from the LuaRocks install path to your project path.

**Comment by Sasanidas** [comment]
Yes indeed I tried but I don't found it a very elegant solution, still, if it cannot be bundle for Steam for example, I don't think it makes too much sense to use it.

Thanks for the quick answer :+1:

**Comment by ShalokShalom** [comment]
> It is possible to add your own package loader to look for Lua modules in other locations (https://www.lua.org/manual/5.1/manual.html#pdf-package.loaders).

Why is that so? 

Instead of removing require, you could just remove the elements that load lua files from disk, from package.loaders.

I guess you'd also want to remove the one that loads C modules.

The current way makes Defold incompatible with alternative Lua languages, who rely on it.

**Comment by britzl** [comment]
Defold is built as a cross platform game engine. When you bundle your game for html5 or mobile or console you need to have all of your assets, scripts and Lua modules in your application bundle. There's no concept of package managers or alternative loaders or C modules for that matter. We have not designed Defold to work with LuaRocks out of the box because that is simply not how 99% of our users use Lua in Defold. Our users add the Lus modules they need to their project or to a project dependency.

**Comment by ShalokShalom** [comment]
Love2D ships to the web and has support for package managing, how comes, that Defold has not? Love2D supports languages such as Fennel, why can't that be the case with Defold?
