### ISSUE TITLE
Shader input ordering issue when building with bob

### ISSUE THREAD

**Issue by JCash** [defold/defold#9132]
In the editor, the build works fine, but when building with bob, it fails.

Setup:
* Tested with bob 1.9.0
* Test project https://github.com/Dragosha/defold-things/tree/master (commit: 501f934acc773fe3f2ed2e0788a1c18bd80001b0)
* Use Vulkan backend

Cmd
```
java -jar ../../../../bob_1.9.0.jar --platform=x86_64-macos --architectures=x86_64-macos distclean build --variant=debug
```

Error message:
```
The build failed for the following reasons:
ERROR assets/materials/shadow_debug.material Location mismatch for fragment shader input 'var_texcoord0': The vertex shader specifies the input at location 3, and location 0 in the fragment shader.
```

**Comment by Jhonnyg** [comment]
Solving this is part of the plan to refactor the shader pipeline: https://github.com/defold/defold/issues/9090

The reason it is happening is because we currently only auto-generate resource bindings for a single shader module (vertex, fragment, compute) when using the spirv-toolchain. Instead we should generate the bindings and locations contextually for the combination of vertex and fragment shaders and output that instead of separate .vpc and .fpc resources. The materials should then point to that resource, which will also hold the reflection data for all modules part of the program, which means we don't need individual shader instances per materials, among other improvements.
