### ISSUE TITLE
Run-time functionality to change which collection to load using a collection proxy

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9217]
**Is your feature request related to a problem? Please describe (REQUIRED):**
If a developer wants to have many versions of the same level for A/B tests or deliver new content using Live Update after the build was released, it's become hard to predict how many collection proxies the build should have. 
Even if a ton of collection proxies created in advance, it's still possible that different users need different collection combinations which become super hard to manage.

**Describe the solution you'd like (REQUIRED):**
An ability to specify what exactly a collection should be loaded by a collection proxy, similar to what Defold has for collectionfactories and factories.

**Describe alternatives you've considered (REQUIRED):**
No alternatives for now.

**Additional context (OPTIONAL):**

- take into account that bob count components for worlds
- take into account `missed_resources` detection

**Comment by britzl** [comment]
Something like this perhaps?

```lua
-- collectionproxy.set_collection(url, collection)
-- @param url The collection proxy
-- @param path The path to the new collection

collectionproxy.set_collection("#collectionproxy", "/my/downloaded.collectionc")
msg.post("#collectionproxy", "async_load")
```

Question: What happens with the collection currently referenced by the collection proxy? What if it is loaded? Will it be automatically unloaded? Will `collectionproxy.set_collection()` return an error?

```lua
local ok, err = collectionproxy.set_collection(url, collection)
if not ok then
   print(err) -- "The collection is already loaded, you need to unload it before you can change collection"
   msg.post(url, "unload")
end
```

Question: Since this should only work on collection proxies where the "Exclude" option is checked, what will happen if someone tries to call `collectionproxy.set_collection()` on a collection proxy which hasn't been excluded? Should it return an error? Probably. And if that is the case how do we distinguish between the case when the collection proxy references a loaded collection and the case when the collection proxy does not have the excluded flag set.

I suggest that we automatically unload the collection if changing collection and that we return an error if trying to change collection on a non-excluded collection proxy.

**Comment by AGulev** [comment]
We don't know if collection excluded or not, it's a checkbox on a proxy, not on a collection.
I think we should return error if:
* Collection proxy is already loaded
* Collection proxy doesn't have Excluded checkbox checked

**Comment by britzl** [comment]
> We don't know if collection excluded or not, it's a checkbox on a proxy, not on a collection. I think we should return error if:
> 
> * Collection proxy is already loaded
> * Collection proxy doesn't have Excluded checkbox checked

Good points. I agree with your suggestion!

**Comment by AGulev** [comment]
Hmmm
https://github.com/defold/defold/blob/bc323cb1e3b5c2b4b00f0a3dd2ecbe3059faf866/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/archive/ManifestBuilder.java#L508-L509

That means that collection proxy with such a change will not return missing_resources
But I think even with a workaround when the collection replaced by LU (when collection in updated filled with another content) it's impossible as well.
