### ISSUE TITLE
Add a support for custom_resources in mounted archives

### ISSUE THREAD

**Issue by Filazapovich** [defold/defold#9432]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Defold supports custom resources by [sys.load_resource](https://defold.com/ref/sys/#sys.load_resource:filename) but only for main game bundle. If the game needs to have custom resources delivered with resource archives (https://defold.com/ref/stable/liveupdate/#liveupdate.add_mount:name-uri-priority-callback) all work should be done by a custom code.

**Describe the solution you'd like (REQUIRED):**
`sys.load_resource` (and other api related to custom resources) should check folders from `project.custom_resources` in mounted archives and load custom resource from the first archive by mount priority which contains requested resource in addition to the main game bundle. 

**Describe alternatives you've considered (REQUIRED):**
The game can work with mounted archives by zip library and handle custom resources from them by custom code

**Comment by AGulev** [comment]
I'm sure it works, but I tested anyway:

1. I made a LU archive
2. added a custom file into that archive like 
> zip -u res.zip foo.json

3. After that loaded foo.json like this:
```
local json = sys.load_resource("/foo.json")
```
4. It works:
![image](https://github.com/user-attachments/assets/a95e1ee4-b2b9-418b-9f9f-f4d99e2bcf90)
I'm closing this issue since it already works as expected
