### ISSUE TITLE
manifest merge fails with firebase analytics and admob in same project.

### ISSUE THREAD

**Issue by kindablissy** [defold/defold#9453]
When building an android application which uses extension-admob and extension-firebase-analytics the job fails to merge their android manifest. 

Although this is specific extensions, I thought this problem should be addressed in the defold tooling as a whole, so i'm opening the issue here.

**To Reproduce (REQUIRED)**
1. Just add admob and extension-firebase-analytics to a project and it will not build due to android manifest conflict.

**Defold version (REQUIRED):**
  - 1.9.2

**Platforms (REQUIRED):**
 -Android

** Engine Log: **
`SEVERE: /tmp/job4531953598647135356/upload/AndroidManifest.xml:32:13-58 Error:
    Attribute property#android.adservices.AD_SERVICES_CONFIG@resource value=(@xml/ga_ad_services_config) from AndroidManifest.xml:32:13-58
    is also present at AndroidManifest.xml:92:13-59 value=(@xml/gma_ad_services_config).
    Suggestion: add 'tools:replace="android:resource"' to <property> element at AndroidManifest.xml to override.
`

**Comment by kindablissy** [comment]
If there is a workaround for this.. I would love to know.

**Comment by ekharkunov** [comment]
Conflict appears because of `play-services-measurement-api:21.5.1` and `play-services-ads-lite:23.0.0`. Both library contains following property in AndroidManifest.xml
```
        <property
            android:name="android.adservices.AD_SERVICES_CONFIG"
            android:resource="@xml/......" />
```
Manifest merger library that we used at Extender side before update didn't merge property tag correctly. After update that bug was fixed but it led to current issue. More information can be found here https://issuetracker.google.com/issues/327696048

Content of `ga_ad_services_config.xml` (from `play-services-measurement-api:21.5.1`)
```xml
<?xml version="1.0" encoding="utf-8"?>
<ad-services-config>
  <!-- Attribution API -->
  <attribution allowAllToAccess="true" />
</ad-services-config>
```
Content of `gma_ad_services_config.xml` (from play-services-ads-lite:23.0.0)
```xml
<?xml version="1.0" encoding="utf-8"?>
<ad-services-config>
  <!-- Attribution API -->
  <attribution allowAllToAccess="true" />

  <!-- Topics API -->
  <topics allowAllToAccess="true" />
</ad-services-config>
```

So correct workaround is:
1. Create custom AndroidManifest.xml (take default AndroidManifest from builtin as a template https://github.com/defold/defold/blob/dev/engine/engine/content/builtins/manifests/android/AndroidManifest.xml)
2. Add following tag as a child of `<application>` tag
```xml
        <property
            android:name="android.adservices.AD_SERVICES_CONFIG"
            android:resource="@xml/gma_ad_services_config"
            tools:replace="android:resource" />
```
That tag mark for manifest merger how to resolve conflict. In our case we mark that config from `play-services-ads-lite:23.0.0` should be taken. It's suitable in current situation because config contains settings for both library (`play-services-ads-lite:23.0.0` and `play-services-measurement-api:21.5.1`).

**Comment by britzl** [comment]
We should document or link to the workarounds somewhere. Perhaps have an entry here:

* https://defold.com/manuals/android/#faq
* https://defold.com/manuals/extensions-manifest-merge-tool/#android
* or directly in the extensions in a Trouble Shooting section

**Comment by britzl** [comment]
This is not an issue on our side, and the solution has been shared here. Closing.
